// Banque issue intégralement du « Livret du citoyen » (édition février 2022,
// ministère de l'Intérieur — Direction générale des étrangers en France).
// Source : https://www.immigration.interieur.gouv.fr/sites/dgef/files/2025-04/Livret-du-citoyen-accessible.pdf
// Chaque question référence la section et la page d'où provient le fait.
// Les libellés respectent ceux du livret pour coller à ce qui est attendu en
// entretien d'assimilation (article 21-24 du code civil).

export type Category =
  | 'symboles'
  | 'valeurs'
  | 'droits_devoirs'
  | 'institutions'
  | 'histoire'
  | 'geographie'
  | 'europe_monde';

export interface Question {
  id: string;
  category: Category;
  prompt: string;
  choices: string[];
  answerIndex: number;
  /** Section du livret (titre court). */
  source: string;
  /** Page du PDF officiel. */
  page: number;
  /** Précision pédagogique, citée du livret quand possible. */
  explanation?: string;
}

export const CATEGORY_LABELS: Record<Category, string> = {
  symboles: 'Symboles',
  valeurs: 'Valeurs',
  droits_devoirs: 'Droits et devoirs',
  institutions: 'Institutions',
  histoire: 'Repères historiques',
  geographie: 'Territoire',
  europe_monde: 'Europe et monde',
};

export const SOURCE_INFO = {
  title: 'Livret du citoyen',
  edition: 'Édition février 2022',
  publisher: 'Ministère de l\'Intérieur — DGEF',
  url: 'https://www.immigration.interieur.gouv.fr/Integration-et-Acces-a-la-nationalite/La-nationalite-francaise/Le-livret-du-citoyen',
};

export const QUESTIONS: Question[] = [
  // ────────────────────────────────────────────────────────────
  // SYMBOLES (p. 4)
  // ────────────────────────────────────────────────────────────
  {
    id: 'sym-devise',
    category: 'symboles',
    prompt: 'Quelle est la devise de la République française ?',
    choices: [
      'Honneur, Patrie, Travail',
      'Liberté, Égalité, Fraternité',
      'Unité, Solidarité, Justice',
      'Travail, Famille, Patrie',
    ],
    answerIndex: 1,
    source: 'La République française',
    page: 4,
    explanation: '« La République garantit le respect des principes de liberté, d\'égalité et de fraternité. Ces trois mots constituent sa devise. »',
  },
  {
    id: 'sym-hymne',
    category: 'symboles',
    prompt: 'Quel est l\'hymne national français ?',
    choices: ['La Parisienne', 'Le Chant des Partisans', 'La Marseillaise', 'Le Chant du départ'],
    answerIndex: 2,
    source: 'La République française',
    page: 4,
    explanation: '« À cette époque (la Révolution), a été composé l\'hymne national, La Marseillaise. »',
  },
  {
    id: 'sym-drapeau',
    category: 'symboles',
    prompt: 'Quelles sont les couleurs du drapeau français ?',
    choices: ['Bleu, blanc, rouge', 'Rouge, blanc, vert', 'Bleu, blanc, vert', 'Bleu, rouge, blanc'],
    answerIndex: 0,
    source: 'La République française',
    page: 4,
    explanation: '« Le drapeau tricolore, bleu, blanc, rouge, date également de la Révolution. »',
  },
  {
    id: 'sym-fete',
    category: 'symboles',
    prompt: 'Quelle est la date de la fête nationale française ?',
    choices: ['Le 8 mai', 'Le 11 novembre', 'Le 14 juillet', 'Le 1er mai'],
    answerIndex: 2,
    source: 'La République française',
    page: 4,
    explanation: '« Le 14 juillet 1790, lors de la fête de la Fédération, cette date du 14 juillet est devenue la date de la fête nationale. »',
  },
  {
    id: 'sym-marianne',
    category: 'symboles',
    prompt: 'Que symbolise Marianne ?',
    choices: [
      'Une reine de France',
      'La République française',
      'La justice française',
      'Une figure mythologique grecque',
    ],
    answerIndex: 1,
    source: 'La République française',
    page: 4,
    explanation: '« La Marianne est devenue le symbole de la République. Sa statue, placée dans toutes les mairies, rappelle la Révolution française. »',
  },
  {
    id: 'sym-langue',
    category: 'symboles',
    prompt: 'Quelle est la langue officielle de la République ?',
    choices: ['Le français et l\'anglais', 'Le français', 'Aucune langue officielle', 'Les langues régionales'],
    answerIndex: 1,
    source: 'La République française',
    page: 4,
    explanation: '« La langue de la République est le français. »',
  },

  // ────────────────────────────────────────────────────────────
  // VALEURS (p. 4-7)
  // ────────────────────────────────────────────────────────────
  {
    id: 'val-liberte-expression',
    category: 'valeurs',
    prompt: 'Avez-vous le droit de tout dire publiquement en France ?',
    choices: [
      'Oui, sans aucune limite',
      'Non, c\'est interdit',
      'Oui, mais avec des limites (injures, diffamation, apologie de crimes…)',
      'Seulement dans le cadre privé',
    ],
    answerIndex: 2,
    source: 'La liberté',
    page: 4,
    explanation: '« La liberté d\'expression est un droit fondamental. Cependant, elle a des limites… Il est ainsi interdit de diffuser des injures, des propos diffamatoires, des provocations à la haine, ou de faire l\'apologie de crimes contre l\'humanité. »',
  },
  {
    id: 'val-egalite-droits',
    category: 'valeurs',
    prompt: 'Selon le principe d\'égalité, qu\'est-ce qui est garanti à tous les citoyens ?',
    choices: [
      'Le même salaire',
      'Les mêmes droits et les mêmes devoirs, quels que soient leur sexe, origine, religion ou opinions',
      'Le même logement',
      'Les mêmes goûts culturels',
    ],
    answerIndex: 1,
    source: 'L\'égalité',
    page: 5,
    explanation: '« Tous les citoyens ont les mêmes droits et les mêmes devoirs quel que soit leur sexe, leur origine, leur religion, leurs opinions ou leur orientation sexuelle. »',
  },
  {
    id: 'val-egalite-hf',
    category: 'valeurs',
    prompt: 'L\'administration peut-elle refuser la nationalité française à une personne ne respectant pas l\'égalité femmes-hommes ?',
    choices: [
      'Non, c\'est une affaire privée',
      'Oui, l\'égalité entre femmes et hommes fait partie des valeurs essentielles de la République',
      'Seulement si la personne n\'est pas mariée',
      'Seulement en cas de violence',
    ],
    answerIndex: 1,
    source: 'L\'égalité',
    page: 5,
    explanation: '« L\'égalité entre les femmes et les hommes fait partie des valeurs essentielles de la République. L\'adhésion à ces valeurs est évaluée au cours de l\'entretien réglementaire. »',
  },
  {
    id: 'val-fraternite',
    category: 'valeurs',
    prompt: 'Comment se traduit concrètement le principe de fraternité en France ?',
    choices: [
      'Par les fêtes de quartier',
      'Par la solidarité entre citoyens, notamment via la sécurité sociale',
      'Par l\'obligation d\'aider ses voisins',
      'Par les associations religieuses',
    ],
    answerIndex: 1,
    source: 'La fraternité',
    page: 6,
    explanation: '« Depuis 1945, le système de sécurité sociale, financé par les cotisations sociales versées en France par les employeurs, les salariés et les non-salariés, ainsi que les impôts, est une illustration de ce principe de fraternité. »',
  },
  {
    id: 'val-discrimination',
    category: 'valeurs',
    prompt: 'Un employeur peut-il refuser d\'embaucher quelqu\'un en raison de ses origines ?',
    choices: [
      'Oui, c\'est son droit',
      'Non, c\'est une discrimination, condamnée par la loi',
      'Oui, sauf pour les emplois publics',
      'Seulement dans les petites entreprises',
    ],
    answerIndex: 1,
    source: 'La fraternité',
    page: 6,
    explanation: '« Un employeur ne peut refuser d\'embaucher un salarié en raison de ses origines, de son âge, de son handicap, de son appartenance à une ethnie ou à une religion, de son sexe ou de son orientation sexuelle. »',
  },
  {
    id: 'val-laicite-def',
    category: 'valeurs',
    prompt: 'Que signifie la laïcité ?',
    choices: [
      'L\'interdiction de toute religion',
      'La séparation des affaires religieuses et publiques, et la liberté de croire ou non',
      'La promotion d\'une religion d\'État',
      'L\'obligation d\'être athée',
    ],
    answerIndex: 1,
    source: 'La laïcité',
    page: 7,
    explanation: '« Elle signifie que les affaires religieuses et les affaires publiques sont clairement séparées… L\'État garantit par ailleurs la liberté religieuse. Chacun est libre de croire ou de ne pas croire. »',
  },
  {
    id: 'val-laicite-1905',
    category: 'valeurs',
    prompt: 'En quelle année la loi de séparation des Églises et de l\'État a-t-elle été votée ?',
    choices: ['1789', '1848', '1905', '1958'],
    answerIndex: 2,
    source: 'La laïcité',
    page: 7,
    explanation: '« Ce principe est ancien : il est consacré par la loi de 1905 qui sépare les Églises de l\'État. »',
  },
  {
    id: 'val-signes-religieux-ecole',
    category: 'valeurs',
    prompt: 'Pourquoi les signes religieux ostensibles sont-ils interdits dans les écoles publiques ?',
    choices: [
      'Pour des raisons d\'hygiène',
      'Parce que l\'école est une institution publique qui doit être neutre face aux religions',
      'Parce qu\'ils gênent les cours',
      'Parce qu\'ils sont chers',
    ],
    answerIndex: 1,
    source: 'La laïcité',
    page: 7,
    explanation: '« La loi du 15 mars 2004 interdit de porter à l\'école des signes ou des tenues qui manifestent ostensiblement (de manière trop visible) l\'appartenance à une religion. En effet, l\'école est une institution publique qui forme tous les citoyens : elle doit donc être neutre face aux religions. »',
  },
  {
    id: 'val-ddhc-art1',
    category: 'valeurs',
    prompt: 'Que dit l\'article 1er de la Déclaration des droits de l\'homme et du citoyen de 1789 ?',
    choices: [
      'Tous les citoyens ont droit au travail',
      'Les hommes naissent et demeurent libres et égaux en droits',
      'L\'éducation est obligatoire',
      'La République est laïque',
    ],
    answerIndex: 1,
    source: 'Déclaration des droits de l\'homme et du citoyen',
    page: 24,
    explanation: '« Art. 1er. Les hommes naissent et demeurent libres et égaux en droits. »',
  },

  // ────────────────────────────────────────────────────────────
  // DROITS ET DEVOIRS (p. 7-8)
  // ────────────────────────────────────────────────────────────
  {
    id: 'dd-vote-age',
    category: 'droits_devoirs',
    prompt: 'À quel âge peut-on voter en France ?',
    choices: ['16 ans', '18 ans', '21 ans', '20 ans'],
    answerIndex: 1,
    source: 'Les droits',
    page: 8,
    explanation: '« Les citoyens bénéficient du droit de vote dès 18 ans. »',
  },
  {
    id: 'dd-emplois-publics',
    category: 'droits_devoirs',
    prompt: 'Comment sont sélectionnés les agents accédant aux emplois publics ?',
    choices: [
      'Selon leur fortune',
      'Selon leur religion',
      'De façon égale, exclusivement selon leurs qualités et compétences',
      'Selon l\'ordre d\'inscription',
    ],
    answerIndex: 2,
    source: 'Les droits',
    page: 8,
    explanation: '« Tous les citoyens ont accès, de façon égale, aux emplois dans l\'administration. Ils sont sélectionnés exclusivement selon leurs qualités et leurs compétences. »',
  },
  {
    id: 'dd-respect-loi',
    category: 'droits_devoirs',
    prompt: 'Selon le livret, quel adage exprime le devoir de respecter la loi ?',
    choices: [
      '« La loi du plus fort »',
      '« Nul n\'est censé ignorer la loi »',
      '« La loi est dure mais c\'est la loi »',
      '« Force reste à la loi »',
    ],
    answerIndex: 1,
    source: 'Les devoirs',
    page: 8,
    explanation: '« En effet, "nul n\'est censé ignorer la loi". Elle s\'applique à tous. »',
  },
  {
    id: 'dd-impots',
    category: 'droits_devoirs',
    prompt: 'Pourquoi les citoyens doivent-ils payer des impôts ?',
    choices: [
      'Pour rembourser une dette personnelle',
      'Pour participer au financement des services publics et de la protection sociale',
      'Uniquement pour financer l\'armée',
      'C\'est facultatif',
    ],
    answerIndex: 1,
    source: 'Les devoirs',
    page: 8,
    explanation: '« Tous les citoyens doivent participer à la hauteur de leurs moyens au financement des services publics en payant des impôts. »',
  },
  {
    id: 'dd-jdc-age',
    category: 'droits_devoirs',
    prompt: 'À quel âge les Françaises et Français doivent-ils se faire recenser pour la Journée défense et citoyenneté ?',
    choices: ['14 ans', '16 ans', '18 ans', '20 ans'],
    answerIndex: 1,
    source: 'Les devoirs — Contribuer à la Défense nationale',
    page: 8,
    explanation: '« À partir de 16 ans, les Françaises et les Français doivent se faire recenser à la mairie pour participer à la Journée défense et citoyenneté. »',
  },
  {
    id: 'dd-info-lois',
    category: 'droits_devoirs',
    prompt: 'Sur quel site officiel peut-on consulter toutes les lois en vigueur en France ?',
    choices: ['service-public.fr', 'legifrance.gouv.fr', 'gouvernement.fr', 'wikipedia.fr'],
    answerIndex: 1,
    source: 'Les citoyens ont des droits et des devoirs',
    page: 7,
    explanation: '« Toutes les lois, souvent regroupées en codes, sont disponibles sur internet : www.legifrance.gouv.fr. »',
  },

  // ────────────────────────────────────────────────────────────
  // INSTITUTIONS (p. 9-11)
  // ────────────────────────────────────────────────────────────
  {
    id: 'inst-republique',
    category: 'institutions',
    prompt: 'Sous quelle République vit la France actuellement ?',
    choices: ['IIIe République', 'IVe République', 'Ve République', 'VIe République'],
    answerIndex: 2,
    source: 'Une organisation politique démocratique',
    page: 9,
    explanation: '« Notre Constitution actuelle est celle de la Ve République, adoptée en 1958. »',
  },
  {
    id: 'inst-mandat-pdt',
    category: 'institutions',
    prompt: 'Quelle est la durée du mandat du Président de la République ?',
    choices: ['4 ans', '5 ans', '6 ans', '7 ans'],
    answerIndex: 1,
    source: 'Les principales institutions de l\'État',
    page: 9,
    explanation: '« Le Président de la République est élu au suffrage universel pour cinq ans. »',
  },
  {
    id: 'inst-1er-ministre',
    category: 'institutions',
    prompt: 'Qui nomme le Premier ministre ?',
    choices: [
      'L\'Assemblée nationale',
      'Le Président de la République',
      'Le Sénat',
      'Le peuple par référendum',
    ],
    answerIndex: 1,
    source: 'Les principales institutions de l\'État',
    page: 9,
    explanation: '« Il (le Président) nomme le Gouvernement, dirigé par le Premier ministre, issu de la majorité aux élections législatives. »',
  },
  {
    id: 'inst-parlement',
    category: 'institutions',
    prompt: 'De quoi est composé le Parlement français ?',
    choices: [
      'De l\'Assemblée nationale et du Sénat',
      'Du Sénat et du Conseil constitutionnel',
      'De l\'Assemblée nationale uniquement',
      'Du Conseil d\'État et du Sénat',
    ],
    answerIndex: 0,
    source: 'Les principales institutions de l\'État',
    page: 9,
    explanation: '« Le Parlement, composé de l\'Assemblée nationale et du Sénat, vote les lois et contrôle le Gouvernement. »',
  },
  {
    id: 'inst-deputes-mandat',
    category: 'institutions',
    prompt: 'Tous les combien d\'années sont élus les députés à l\'Assemblée nationale ?',
    choices: ['Tous les 4 ans', 'Tous les 5 ans', 'Tous les 6 ans', 'Tous les 7 ans'],
    answerIndex: 1,
    source: 'Les principales institutions de l\'État',
    page: 9,
    explanation: '« Les députés à l\'Assemblée nationale sont élus tous les cinq ans lors des élections législatives. »',
  },
  {
    id: 'inst-senat-election',
    category: 'institutions',
    prompt: 'Comment sont élus les sénateurs ?',
    choices: [
      'Au suffrage universel direct',
      'Au suffrage universel indirect, pour 6 ans',
      'Nommés par le Président',
      'Tirés au sort',
    ],
    answerIndex: 1,
    source: 'Les principales institutions de l\'État',
    page: 9,
    explanation: '« Les sénateurs sont élus au suffrage universel indirect pour un mandat de 6 ans. »',
  },
  {
    id: 'inst-justice-role',
    category: 'institutions',
    prompt: 'Que fait la justice en France ?',
    choices: [
      'Elle vote les lois',
      'Elle règle les litiges et sanctionne les infractions aux règles de droit',
      'Elle nomme le gouvernement',
      'Elle organise les élections',
    ],
    answerIndex: 1,
    source: 'Les principales institutions de l\'État',
    page: 9,
    explanation: '« La justice est rendue par les juges. Elle règle les litiges entre les particuliers ou les entreprises, et entre les citoyens et l\'administration. Elle sanctionne les infractions aux règles de droit par des peines prévues par la loi. »',
  },
  {
    id: 'inst-separation-pouvoirs',
    category: 'institutions',
    prompt: 'Sur quel principe sont fondées les institutions françaises ?',
    choices: [
      'L\'unité du pouvoir',
      'La séparation des pouvoirs exécutif, législatif et judiciaire',
      'La hiérarchie des partis',
      'Le pouvoir absolu du président',
    ],
    answerIndex: 1,
    source: 'Une organisation politique démocratique',
    page: 9,
    explanation: '« Nos institutions sont fondées sur la séparation des pouvoirs exécutif et législatif et de l\'autorité judiciaire : ces pouvoirs et la Justice ne doivent pas être exercés par la même autorité. »',
  },
  {
    id: 'inst-communes-nb',
    category: 'institutions',
    prompt: 'Combien la France compte-t-elle de communes (au 1er janvier 2021) ?',
    choices: ['Environ 5 000', 'Environ 15 000', 'Environ 35 000', 'Environ 100 000'],
    answerIndex: 2,
    source: 'La commune',
    page: 11,
    explanation: '« La France compte 34 965 communes au 1er janvier 2021. »',
  },
  {
    id: 'inst-commune-role',
    category: 'institutions',
    prompt: 'Qui administre une commune ?',
    choices: [
      'Le préfet',
      'Le maire et le conseil municipal',
      'Le département',
      'Le ministre de l\'Intérieur',
    ],
    answerIndex: 1,
    source: 'La commune',
    page: 11,
    explanation: '« Elles sont administrées par un maire et un conseil municipal. »',
  },
  {
    id: 'inst-departements-nb',
    category: 'institutions',
    prompt: 'Combien la France compte-t-elle de départements ?',
    choices: ['90', '95', '101', '110'],
    answerIndex: 2,
    source: 'Le département',
    page: 11,
    explanation: '« La France compte 101 départements. »',
  },
  {
    id: 'inst-regions-nb',
    category: 'institutions',
    prompt: 'Combien la France métropolitaine compte-t-elle de régions ?',
    choices: ['10', '13', '17', '22'],
    answerIndex: 1,
    source: 'La région',
    page: 11,
    explanation: '« Les 13 régions métropolitaines sont administrées par les conseils régionaux. »',
  },
  {
    id: 'inst-prefet',
    category: 'institutions',
    prompt: 'Qui représente l\'État dans les départements et les régions ?',
    choices: ['Le maire', 'Le président de région', 'Le préfet', 'Le ministre de l\'Intérieur'],
    answerIndex: 2,
    source: 'L\'outre-mer',
    page: 11,
    explanation: '« L\'État est représenté par les préfets (ou par les hauts-commissaires dans certaines collectivités d\'outre-mer). »',
  },

  // ────────────────────────────────────────────────────────────
  // HISTOIRE (p. 12-19)
  // ────────────────────────────────────────────────────────────
  {
    id: 'hist-clovis',
    category: 'histoire',
    prompt: 'Qui a unifié les royaumes des peuples francs au Ve siècle ?',
    choices: ['Charlemagne', 'Clovis', 'Vercingétorix', 'Hugues Capet'],
    answerIndex: 1,
    source: 'Repères historiques — Moyen-Âge',
    page: 13,
    explanation: '« Clovis (466-511) unifie les royaumes de différents peuples francs. C\'est une étape importante dans la construction de l\'unité du territoire français. Il adopte la religion chrétienne. »',
  },
  {
    id: 'hist-jeanne',
    category: 'histoire',
    prompt: 'Pendant quelle guerre Jeanne d\'Arc a-t-elle conduit les troupes françaises ?',
    choices: [
      'La guerre de Cent Ans contre l\'Angleterre',
      'La guerre de Trente Ans',
      'Les guerres de religion',
      'La guerre franco-prussienne',
    ],
    answerIndex: 0,
    source: 'Repères historiques — Moyen-Âge',
    page: 13,
    explanation: '« Jeanne d\'Arc (1412-1431). Pendant la guerre de Cent-Ans contre l\'Angleterre, cette jeune paysanne conduit les troupes françaises à la libération d\'une partie du territoire français. »',
  },
  {
    id: 'hist-henri4-edit',
    category: 'histoire',
    prompt: 'Quel édit Henri IV a-t-il signé en 1598 ?',
    choices: [
      'L\'édit de Nantes, qui accorde aux protestants la liberté d\'exercer leur religion',
      'L\'édit de Versailles',
      'L\'édit de Fontainebleau',
      'L\'édit de Paris',
    ],
    answerIndex: 0,
    source: 'Repères historiques — Moyen-Âge',
    page: 13,
    explanation: '« Henri IV (1553-1610), par l\'édit de Nantes de 1598, accorde aux protestants la liberté d\'exercer leur religion et rétablit la paix religieuse. »',
  },
  {
    id: 'hist-louis14',
    category: 'histoire',
    prompt: 'Comment est qualifié le règne de Louis XIV (1643-1715) ?',
    choices: [
      'Une République parlementaire',
      'Une monarchie absolue, où le roi concentre tous les pouvoirs',
      'Une démocratie',
      'Une dictature militaire',
    ],
    answerIndex: 1,
    source: 'Repères historiques — Époque moderne',
    page: 14,
    explanation: '« Règne de Louis XIV (1643-1715). La France est alors dirigée par une monarchie absolue. Le roi concentre tous les pouvoirs. »',
  },
  {
    id: 'hist-lumieres',
    category: 'histoire',
    prompt: 'Quels philosophes des Lumières ont combattu pour la tolérance et la liberté de pensée ?',
    choices: [
      'Descartes, Pascal, Montaigne',
      'Rousseau, Voltaire, Diderot',
      'Sartre, Camus, Aron',
      'Bergson, Comte, Renan',
    ],
    answerIndex: 1,
    source: 'Repères historiques — Époque moderne',
    page: 14,
    explanation: '« Les philosophes des Lumières — Rousseau, Voltaire, Diderot — combattent à travers leurs œuvres pour la tolérance et la liberté de pensée. »',
  },
  {
    id: 'hist-revolution',
    category: 'histoire',
    prompt: 'En quelle année a eu lieu la Révolution française ?',
    choices: ['1689', '1789', '1815', '1848'],
    answerIndex: 1,
    source: 'Repères historiques — Révolution française',
    page: 14,
    explanation: '« En 1789, le peuple se révolte contre la monarchie absolue. En 1792, la 1re République est proclamée. »',
  },
  {
    id: 'hist-ddhc-date',
    category: 'histoire',
    prompt: 'Quand la Déclaration des droits de l\'homme et du citoyen a-t-elle été adoptée ?',
    choices: ['1789', '1804', '1848', '1958'],
    answerIndex: 0,
    source: 'Repères historiques — Révolution française',
    page: 14,
    explanation: '« Cette période (la Révolution) est à l\'origine de nos valeurs républicaines, avec la Déclaration des Droits de l\'Homme et du Citoyen de 1789. »',
  },
  {
    id: 'hist-napoleon',
    category: 'histoire',
    prompt: 'À qui doit-on notamment le Code civil ?',
    choices: ['Louis XIV', 'Napoléon Ier', 'Charles de Gaulle', 'Jules Ferry'],
    answerIndex: 1,
    source: 'Repères historiques — Empire',
    page: 15,
    explanation: '« Napoléon Ier (1769-1821) dirige la France pendant près de 15 ans. Il mène de nombreuses guerres en Europe. On lui doit notamment le Code civil. »',
  },
  {
    id: 'hist-esclavage',
    category: 'histoire',
    prompt: 'En quelle année l\'esclavage a-t-il été aboli en France ?',
    choices: ['1789', '1815', '1848', '1905'],
    answerIndex: 2,
    source: 'Repères historiques',
    page: 15,
    explanation: '« 1848 : abolition de l\'esclavage. »',
  },
  {
    id: 'hist-hugo',
    category: 'histoire',
    prompt: 'Qui a écrit Les Misérables et Notre-Dame de Paris ?',
    choices: ['Émile Zola', 'Victor Hugo', 'Honoré de Balzac', 'Marcel Proust'],
    answerIndex: 1,
    source: 'Repères historiques — XIXe siècle',
    page: 15,
    explanation: '« Victor Hugo (1802-1885)… Il a écrit Les Misérables et Notre-Dame de Paris. »',
  },
  {
    id: 'hist-ferry',
    category: 'histoire',
    prompt: 'Qui est à l\'origine de l\'enseignement public, gratuit, obligatoire et laïc dans les années 1880 ?',
    choices: ['Jean Jaurès', 'Jules Ferry', 'Léon Gambetta', 'Émile Combes'],
    answerIndex: 1,
    source: 'Repères historiques — XIXe siècle',
    page: 15,
    explanation: '« Jules Ferry, ministre de l\'Instruction publique au début des années 1880 est à l\'origine de l\'enseignement public, gratuit et laïc. »',
  },
  {
    id: 'hist-ww1-jour-ferie',
    category: 'histoire',
    prompt: 'Quel jour férié commémore la fin de la Première Guerre mondiale ?',
    choices: ['Le 8 mai', 'Le 14 juillet', 'Le 11 novembre', 'Le 6 juin'],
    answerIndex: 2,
    source: 'Repères historiques — XXe siècle',
    page: 16,
    explanation: '« Le 11 novembre est un jour férié en commémoration de la fin de la Première Guerre mondiale. »',
  },
  {
    id: 'hist-ww2-jour-ferie',
    category: 'histoire',
    prompt: 'Quel jour férié commémore la fin de la Seconde Guerre mondiale ?',
    choices: ['Le 8 mai', 'Le 14 juillet', 'Le 11 novembre', 'Le 6 juin'],
    answerIndex: 0,
    source: 'Repères historiques — XXe siècle',
    page: 16,
    explanation: '« Le 8 mai est un jour férié en commémoration de la fin de la Seconde Guerre mondiale. »',
  },
  {
    id: 'hist-vichy',
    category: 'histoire',
    prompt: 'Qu\'est-ce que le régime de Vichy (1940-1944) ?',
    choices: [
      'La République restaurée',
      'Un régime non démocratique du maréchal Pétain qui a collaboré avec l\'Allemagne nazie',
      'Le gouvernement provisoire de la Résistance',
      'Une monarchie temporaire',
    ],
    answerIndex: 1,
    source: 'Repères historiques — XXe siècle',
    page: 16,
    explanation: '« Suite à la défaite française face à l\'Allemagne, le maréchal Pétain met en place un régime non démocratique dont la capitale est Vichy. Le régime collabore avec l\'Allemagne nazie et porte donc une part de responsabilité dans la déportation des Juifs. »',
  },
  {
    id: 'hist-degaulle',
    category: 'histoire',
    prompt: 'Qui était Charles de Gaulle ?',
    choices: [
      'Un roi de France',
      'Le chef de la résistance française et l\'origine de la Ve République en 1958',
      'Un philosophe des Lumières',
      'Un compositeur du XIXe siècle',
    ],
    answerIndex: 1,
    source: 'Repères historiques — XXe siècle',
    page: 16,
    explanation: '« Charles de Gaulle (1890-1970). Chef de la résistance française contre les armées allemandes… il est, avec les alliés, à l\'origine de la libération de la France. Bien après la guerre, en 1958, il est à l\'origine de nos institutions actuelles (la Ve République). »',
  },
  {
    id: 'hist-decolonisation',
    category: 'histoire',
    prompt: 'Quelles guerres marquent la décolonisation française (1950-1962) ?',
    choices: [
      'Les guerres napoléoniennes',
      'Les guerres d\'Indochine et d\'Algérie',
      'Les guerres de religion',
      'Les guerres mondiales',
    ],
    answerIndex: 1,
    source: 'Repères historiques — Décolonisation',
    page: 17,
    explanation: '« La décolonisation française débute en Asie et s\'étend à l\'Afrique. Ce processus a donné lieu à des guerres comme celles d\'Indochine et d\'Algérie. »',
  },
  {
    id: 'hist-traite-rome',
    category: 'histoire',
    prompt: 'Quel traité instaure la Communauté économique européenne en 1957 ?',
    choices: [
      'Le traité de Maastricht',
      'Le traité de Rome',
      'Le traité de Lisbonne',
      'Le traité de Versailles',
    ],
    answerIndex: 1,
    source: 'Repères historiques',
    page: 17,
    explanation: '« Traité de Rome (1957). Instaure la Communauté économique européenne entre six pays d\'Europe, dont la France. »',
  },
  {
    id: 'hist-majorite',
    category: 'histoire',
    prompt: 'En quelle année l\'âge de la majorité a-t-il été fixé à 18 ans en France ?',
    choices: ['1944', '1968', '1974', '1981'],
    answerIndex: 2,
    source: 'Repères historiques',
    page: 17,
    explanation: '« L\'âge de la majorité est fixé à 18 ans (1974). »',
  },
  {
    id: 'hist-ivg',
    category: 'histoire',
    prompt: 'Qui a préparé la loi de 1975 autorisant l\'interruption volontaire de grossesse ?',
    choices: ['Françoise Giroud', 'Simone Veil', 'Marie Curie', 'Olympe de Gouges'],
    answerIndex: 1,
    source: 'Repères historiques',
    page: 17,
    explanation: '« Loi sur l\'interruption volontaire de grossesse (1975), préparée par Simone Veil. Elle autorise l\'avortement. »',
  },
  {
    id: 'hist-peine-mort',
    category: 'histoire',
    prompt: 'En quelle année la peine de mort a-t-elle été abolie en France ?',
    choices: ['1944', '1958', '1975', '1981'],
    answerIndex: 3,
    source: 'Repères historiques',
    page: 17,
    explanation: '« Abolition de la peine de mort (1981) en France. »',
  },
  {
    id: 'hist-mai68',
    category: 'histoire',
    prompt: 'Par qui le mouvement social de Mai 68 a-t-il été initié ?',
    choices: ['Par les militaires', 'Par des étudiants', 'Par les agriculteurs', 'Par le gouvernement'],
    answerIndex: 1,
    source: 'Repères historiques',
    page: 17,
    explanation: '« Mai 68. Le mouvement social est initié par des étudiants. Il s\'étend aux salariés et au monde ouvrier. »',
  },
  {
    id: 'hist-curie',
    category: 'histoire',
    prompt: 'Quelle physicienne d\'origine polonaise, inhumée au Panthéon, a découvert la radioactivité ?',
    choices: ['Simone Veil', 'Marie Curie', 'Andrée Chedid', 'Françoise Giroud'],
    answerIndex: 1,
    source: 'La France est riche… de nombreux apports étrangers',
    page: 18,
    explanation: '« Marie Curie (1867-1934). Physicienne née en Pologne. On lui doit la découverte de la radioactivité, au début du XXe siècle. Elle est inhumée au Panthéon. »',
  },
  {
    id: 'hist-baker',
    category: 'histoire',
    prompt: 'Quelle artiste d\'origine américaine, naturalisée française, s\'est illustrée dans la Résistance ?',
    choices: ['Dalida', 'Joséphine Baker', 'Miriam Makeba', 'Andrée Chedid'],
    answerIndex: 1,
    source: 'La France est riche… de nombreux apports étrangers',
    page: 18,
    explanation: '« Joséphine Baker (1906-1975). D\'origine américaine, elle est la première chanteuse, danseuse et meneuse de revue noire reconnue. Elle s\'illustra dans la Résistance lors de la Seconde Guerre Mondiale. »',
  },

  // ────────────────────────────────────────────────────────────
  // GÉOGRAPHIE / TERRITOIRE (p. 22-23, 11)
  // ────────────────────────────────────────────────────────────
  {
    id: 'geo-population',
    category: 'geographie',
    prompt: 'Combien la France comptait-elle d\'habitants en 2021 (source INSEE) ?',
    choices: ['52 millions', '60 millions', '67,4 millions', '75 millions'],
    answerIndex: 2,
    source: 'Quelques caractéristiques de la France',
    page: 22,
    explanation: '« En 2021, la France compte 67,4 millions d\'habitants (source INSEE). »',
  },
  {
    id: 'geo-superficie',
    category: 'geographie',
    prompt: 'Quelle est la superficie du territoire français (métropole et outre-mer) ?',
    choices: ['350 000 km²', '550 000 km²', '675 000 km²', '900 000 km²'],
    answerIndex: 2,
    source: 'Quelques caractéristiques de la France',
    page: 22,
    explanation: '« Son territoire s\'étend sur 675 000 km², en métropole et outre-mer. »',
  },
  {
    id: 'geo-mont-blanc',
    category: 'geographie',
    prompt: 'Quel est le plus haut sommet de la chaîne des Alpes (et d\'Europe occidentale) ?',
    choices: ['Le Mont-Blanc (4 810 m)', 'L\'Aiguille du Midi', 'Le Mont Cervin', 'Le pic du Midi'],
    answerIndex: 0,
    source: 'Quelques sites remarquables',
    page: 22,
    explanation: '« Le Mont-Blanc, sommet de la chaîne des Alpes, est la plus haute montagne d\'Europe (4 810 m). »',
  },
  {
    id: 'geo-msm',
    category: 'geographie',
    prompt: 'Où se trouve le Mont-Saint-Michel ?',
    choices: ['En Bretagne', 'En Normandie', 'En Provence', 'En Alsace'],
    answerIndex: 1,
    source: 'Quelques sites remarquables',
    page: 22,
    explanation: '« Le Mont-Saint-Michel est un îlot rocheux situé en Normandie dans une baie, sur lequel s\'élève une abbaye. Il est classé au patrimoine mondial de l\'humanité par l\'UNESCO. »',
  },
  {
    id: 'geo-fleuve-plus-long',
    category: 'geographie',
    prompt: 'Quel est le plus long fleuve français ?',
    choices: ['La Seine', 'La Loire', 'Le Rhône', 'La Garonne'],
    answerIndex: 1,
    source: 'Quelques sites remarquables',
    page: 22,
    explanation: '« La Loire est le plus long fleuve français. »',
  },
  {
    id: 'geo-fleuves',
    category: 'geographie',
    prompt: 'Lequel de ces cours d\'eau ne fait pas partie des fleuves importants de France cités dans le livret ?',
    choices: ['La Loire', 'La Seine', 'Le Rhin', 'Le Danube'],
    answerIndex: 3,
    source: 'Quelques sites remarquables',
    page: 22,
    explanation: '« La France est parcourue par des fleuves importants : la Loire, la Seine, la Garonne, le Rhône, le Rhin. »',
  },
  {
    id: 'geo-domtom-drom',
    category: 'geographie',
    prompt: 'Lequel de ces territoires est à la fois département et région d\'outre-mer ?',
    choices: ['La Polynésie française', 'La Guadeloupe', 'La Nouvelle-Calédonie', 'Saint-Martin'],
    answerIndex: 1,
    source: 'L\'outre-mer',
    page: 11,
    explanation: '« 5 (territoires) sont à la fois des départements et des régions (Guadeloupe, Guyane, Martinique, Mayotte et la Réunion). »',
  },
  {
    id: 'geo-outre-mer-nb',
    category: 'geographie',
    prompt: 'Combien de territoires d\'outre-mer la France compte-t-elle ?',
    choices: ['5', '7', '12', '17'],
    answerIndex: 2,
    source: 'L\'outre-mer',
    page: 11,
    explanation: '« La France compte 12 territoires d\'outre-mer : 5 sont à la fois des départements et des régions… 7 sont des collectivités d\'outre-mer. »',
  },

  // ────────────────────────────────────────────────────────────
  // EUROPE ET MONDE (p. 20-21)
  // ────────────────────────────────────────────────────────────
  {
    id: 'eu-membres',
    category: 'europe_monde',
    prompt: 'Combien d\'États composent l\'Union européenne ?',
    choices: ['12', '19', '27', '32'],
    answerIndex: 2,
    source: 'Les citoyens français sont des citoyens européens',
    page: 20,
    explanation: '« Aujourd\'hui, l\'Union compte 27 États membres, qui partagent des principes démocratiques. »',
  },
  {
    id: 'eu-citoyennete-1992',
    category: 'europe_monde',
    prompt: 'Depuis quelle année les citoyens français sont-ils aussi citoyens européens ?',
    choices: ['1957', '1981', '1992', '2000'],
    answerIndex: 2,
    source: 'Les citoyens français sont des citoyens européens',
    page: 20,
    explanation: '« Depuis 1992, les citoyens français sont aussi citoyens européens. »',
  },
  {
    id: 'eu-euro',
    category: 'europe_monde',
    prompt: 'Depuis quelle année la France utilise-t-elle l\'euro ?',
    choices: ['1992', '2000', '2002', '2010'],
    answerIndex: 1,
    source: 'Les citoyens français sont des citoyens européens',
    page: 20,
    explanation: '« Depuis 2000, la France partage avec 18 autres pays membres de l\'Union européenne une monnaie unique : l\'Euro. »',
  },
  {
    id: 'eu-drapeau',
    category: 'europe_monde',
    prompt: 'Que symbolisent les 12 étoiles du drapeau européen ?',
    choices: [
      'Les 12 pays fondateurs',
      'Les idéaux d\'unité et d\'harmonie entre les Européens',
      'Les 12 mois de l\'année',
      'Les 12 langues officielles',
    ],
    answerIndex: 1,
    source: 'Les citoyens français sont des citoyens européens',
    page: 17,
    explanation: '« Le drapeau européen, constitué de 12 étoiles, symbolise les idéaux d\'unité et d\'harmonie entre les Européens. »',
  },
  {
    id: 'eu-onu',
    category: 'europe_monde',
    prompt: 'Quel statut la France a-t-elle au sein de l\'Organisation des Nations Unies ?',
    choices: [
      'Observateur',
      'Membre temporaire',
      'Membre permanent du Conseil de sécurité',
      'Pays candidat',
    ],
    answerIndex: 2,
    source: 'La France est la sixième puissance économique mondiale',
    page: 20,
    explanation: '« Elle est membre permanent du Conseil de sécurité de l\'Organisation des Nations Unies (ONU). »',
  },
  {
    id: 'eu-rang-eco',
    category: 'europe_monde',
    prompt: 'Quel rang la France occupe-t-elle parmi les puissances économiques mondiales (selon le livret) ?',
    choices: ['3e', '5e', '6e', '10e'],
    answerIndex: 2,
    source: 'La France est la sixième puissance économique mondiale',
    page: 20,
    explanation: '« La France est la sixième puissance économique mondiale. »',
  },
  {
    id: 'eu-langue-monde',
    category: 'europe_monde',
    prompt: 'Par combien de personnes le français est-il parlé couramment dans le monde ?',
    choices: ['50 millions', '100 millions', '200 millions', '500 millions'],
    answerIndex: 2,
    source: 'La langue française',
    page: 20,
    explanation: '« Le français est parlé couramment par 200 millions de personnes dans le monde. »',
  },
  {
    id: 'eu-tourisme',
    category: 'europe_monde',
    prompt: 'Quel rang occupe la France comme destination touristique mondiale ?',
    choices: ['1er', '3e', '5e', '10e'],
    answerIndex: 0,
    source: 'L\'importance économique de la France',
    page: 21,
    explanation: '« La France est célèbre pour ses monuments et sa culture : c\'est la première destination touristique au monde. »',
  },
];
