// Banque alignée sur la liste officielle des questions de connaissance de
// l'examen civique (mention « carte de résident » / naturalisation), publiée
// par le ministère de l'Intérieur sur formation-civique.interieur.gouv.fr.
//
// Les énoncés sont repris à l'identique du site officiel. Les 4 choix et la
// bonne réponse — que le ministère ne publie pas — sont rédigés à partir du
// Livret du citoyen, de la Constitution de 1958, du Code civil/pénal et de
// service-public.fr.
//
// 209 questions de connaissance, réparties en 5 thématiques officielles :
//   - Principes et valeurs de la République (40)
//   - Système institutionnel et politique (50)
//   - Droits et devoirs (38)
//   - Histoire, géographie et culture (49)
//   - Vivre dans la société française (32)
//
// L'examen réel = 40 QCM (28 connaissance + 12 mises en situation
// confidentielles), 45 min max, seuil 80 % (32/40).
//
// Statut : premier jet. Les questions où la bonne réponse est ambiguë sont
// listées dans BANK_REVIEW.md à la racine du repo.

export type Category =
  | 'principes'
  | 'institutions'
  | 'droits'
  | 'histoire'
  | 'societe';

export interface Question {
  id: string;
  category: Category;
  prompt: string;
  choices: string[];
  answerIndex: number;
  /** Source courte de la bonne réponse (livret, constitution, code, etc.). */
  source: string;
  /** Page du Livret du citoyen quand applicable. */
  page?: number;
  explanation?: string;
}

export const CATEGORY_LABELS: Record<Category, string> = {
  principes: 'Principes et valeurs de la République',
  institutions: 'Système institutionnel et politique',
  droits: 'Droits et devoirs',
  histoire: 'Histoire, géographie et culture',
  societe: 'Vivre dans la société française',
};

export const SOURCE_INFO = {
  title: 'Liste officielle des questions de connaissance — Examen civique CR',
  publisher: 'Ministère de l\'Intérieur — DGEF',
  url: 'https://formation-civique.interieur.gouv.fr/examen-civique/liste-officielle-des-questions-de-connaissance-cr/',
};

export const QUESTIONS: Question[] = [
  // ────────────────────────────────────────────────────────────────────────
  // PRINCIPES ET VALEURS DE LA RÉPUBLIQUE (40)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: 'p-csutq',
    category: 'principes',
    prompt: 'Parmi les propositions suivantes, laquelle constitue une participation citoyenne ?',
    choices: [
      'Refuser de payer ses impôts',
      'Voter aux élections',
      'Critiquer publiquement ses voisins',
      'Ignorer les décisions de l\'administration',
    ],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'p-g8ls',
    category: 'principes',
    prompt: 'Que garantit la liberté d\'expression ?',
    choices: [
      'Le droit de tout dire sans aucune limite',
      'Le devoir de se taire en public',
      'Le droit d\'exprimer ses opinions, dans les limites fixées par la loi',
      'Le droit d\'imposer son opinion à autrui',
    ],
    answerIndex: 2,
    source: 'DDHC 1789, art. 11',
  },
  {
    id: 'p-f064t',
    category: 'principes',
    prompt: 'À quoi sert un titre de séjour ?',
    choices: [
      'À donner la nationalité française',
      'À autoriser un étranger à résider légalement en France',
      'À voyager gratuitement dans l\'Union européenne',
      'À voter aux élections',
    ],
    answerIndex: 1,
    source: 'Service-public.fr',
  },
  {
    id: 'p-d7jpr',
    category: 'principes',
    prompt: 'La liberté de circulation permet à toute personne de :',
    choices: [
      'Conduire sans permis',
      'Voyager sans aucun document d\'identité',
      'Se déplacer librement sur le territoire français',
      'Entrer dans tout pays sans visa',
    ],
    answerIndex: 2,
    source: 'Livret du citoyen',
  },
  {
    id: 'p-dnrf2',
    category: 'principes',
    prompt: 'Sur quel site internet peut-on retrouver le symbole de la République française ?',
    choices: ['tiktok.com', 'wikipedia.fr', 'elysee.fr', 'meteofrance.com'],
    answerIndex: 2,
    source: 'elysee.fr — Symboles de la République',
  },
  {
    id: 'p-2hqjg',
    category: 'principes',
    prompt: 'Complétez ces paroles de la Marseillaise : « Aux armes [...] ! Formez vos bataillons »',
    choices: ['enfants', 'citoyens', 'soldats', 'Français'],
    answerIndex: 1,
    source: 'Hymne national',
  },
  {
    id: 'p-91auu',
    category: 'principes',
    prompt: 'Complétez les paroles de la Marseillaise : « Allons enfants de la patrie [...] »',
    choices: [
      'À l\'attaque, en avant marche',
      'Le jour de gloire est arrivé',
      'Vive la République française',
      'Pour la liberté nous combattrons',
    ],
    answerIndex: 1,
    source: 'Hymne national',
  },
  {
    id: 'p-drqk0',
    category: 'principes',
    prompt: 'En application de la liberté individuelle, quelle proposition est correcte ? Une personne peut :',
    choices: [
      'Frapper son enfant pour le punir',
      'Forcer une autre personne à se marier',
      'Choisir librement sa profession et son lieu de résidence',
      'Refuser de respecter la loi',
    ],
    answerIndex: 2,
    source: 'Livret du citoyen',
  },
  {
    id: 'p-c9u7s',
    category: 'principes',
    prompt: 'Concernant la pratique de la religion, quelle proposition est correcte ?',
    choices: [
      'Toutes les religions sont interdites en France',
      'La République impose une religion d\'État',
      'Chacun est libre de pratiquer ou non une religion, dans le respect de la loi',
      'La pratique religieuse est obligatoire',
    ],
    answerIndex: 2,
    source: 'Loi de 1905',
  },
  {
    id: 'p-8h4qe',
    category: 'principes',
    prompt: 'En tant que parent, peut-on refuser que son enfant participe aux cours de sport à l\'école car ils sont mixtes ?',
    choices: [
      'Oui, sur simple demande des parents',
      'Oui, si la famille pratique une religion',
      'Oui, si l\'enfant est une fille',
      'Non, l\'enfant doit suivre tous les cours, y compris les cours mixtes',
    ],
    answerIndex: 3,
    source: 'Charte de la laïcité à l\'école',
  },
  {
    id: 'p-an3p4',
    category: 'principes',
    prompt: 'Quelle est la devise de la France ?',
    choices: [
      'Travail, Famille, Patrie',
      'Liberté, Égalité, Fraternité',
      'Honneur, Patrie, Travail',
      'Unité, Solidarité, Justice',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958, art. 2',
    page: 4,
  },
  {
    id: 'p-enqu8',
    category: 'principes',
    prompt: 'La répudiation de sa femme est :',
    choices: [
      'Une procédure légale de divorce',
      'Autorisée sous certaines conditions',
      'Reconnue par l\'état civil français',
      'Interdite en France',
    ],
    answerIndex: 3,
    source: 'Code civil',
  },
  {
    id: 'p-a0080',
    category: 'principes',
    prompt: 'Les impôts permettent de financer les dépenses publiques. Quelle proposition est correcte ?',
    choices: [
      'Les impôts sont facultatifs',
      'Tout le monde doit payer ses impôts en fonction de ses ressources',
      'Seuls les Français paient des impôts en France',
      'Les étrangers en sont dispensés',
    ],
    answerIndex: 1,
    source: 'DDHC 1789, art. 13',
  },
  {
    id: 'p-f2b2i',
    category: 'principes',
    prompt: 'Peut-on brûler publiquement un drapeau français ?',
    choices: [
      'Oui, c\'est de la liberté d\'expression',
      'Oui, lors de manifestations autorisées',
      'Non, c\'est interdit et puni par la loi',
      'Oui, avec autorisation préfectorale',
    ],
    answerIndex: 2,
    source: 'Code pénal, art. 433-5-1',
  },
  {
    id: 'p-cap94',
    category: 'principes',
    prompt: 'Que fait l\'État pour lutter contre les discriminations ?',
    choices: [
      'Rien, c\'est un sujet privé',
      'Il les sanctionne par la loi et soutient les victimes',
      'Il les autorise dans le secteur privé',
      'Il interdit toute prise en compte de l\'origine',
    ],
    answerIndex: 1,
    source: 'Code pénal, art. 225-1 et s.',
  },
  {
    id: 'p-3ksk8',
    category: 'principes',
    prompt: 'Que représente Marianne ?',
    choices: [
      'Une reine de France',
      'La Justice',
      'La République française',
      'Une figure mythologique grecque',
    ],
    answerIndex: 2,
    source: 'Livret du citoyen',
    page: 4,
  },
  {
    id: 'p-f092r',
    category: 'principes',
    prompt: 'Qu\'est-ce que la liberté d\'association ?',
    choices: [
      'L\'obligation d\'adhérer à un syndicat',
      'Le droit de créer ou d\'adhérer à une association',
      'Le droit de fonder une entreprise',
      'Le devoir de fréquenter ses voisins',
    ],
    answerIndex: 1,
    source: 'Loi du 1er juillet 1901',
  },
  {
    id: 'p-fgi8i',
    category: 'principes',
    prompt: 'Qu\'est-ce que la liberté ?',
    choices: [
      'Faire tout ce que l\'on veut sans aucune limite',
      'Pouvoir faire tout ce qui ne nuit pas à autrui',
      'Obéir aveuglément à l\'État',
      'Choisir son pays de naissance',
    ],
    answerIndex: 1,
    source: 'DDHC 1789, art. 4',
  },
  {
    id: 'p-8iaa3',
    category: 'principes',
    prompt: 'Qu\'est-ce que la Marseillaise ?',
    choices: [
      'Un fleuve français',
      'L\'hymne national français',
      'Un opéra italien',
      'Un chant militaire interdit',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958, art. 2',
    page: 4,
  },
  {
    id: 'p-2hc5n',
    category: 'principes',
    prompt: 'Sur quel document peut-on voir Marianne ?',
    choices: [
      'Sur les passeports américains',
      'Sur les billets de banque suisses',
      'Sur les timbres-poste et les pièces de monnaie françaises',
      'Sur les permis de conduire allemands',
    ],
    answerIndex: 2,
    source: 'Livret du citoyen',
  },
  {
    id: 'p-1qn0n',
    category: 'principes',
    prompt: 'Un employeur refuse d\'embaucher des femmes dans son entreprise. Que dit la loi ?',
    choices: [
      'C\'est autorisé pour les petites entreprises',
      'C\'est autorisé selon le métier',
      'C\'est légal s\'il prévient à l\'avance',
      'C\'est une discrimination interdite et punie par la loi',
    ],
    answerIndex: 3,
    source: 'Code du travail, art. L1132-1',
  },
  {
    id: 'p-92b3u',
    category: 'principes',
    prompt: 'Une des valeurs de la devise républicaine est l\'égalité. Qu\'est-ce que cela signifie ?',
    choices: [
      'Tout le monde a le même salaire',
      'Tous les citoyens ont les mêmes droits et les mêmes devoirs',
      'Tout le monde habite la même ville',
      'Tout le monde a la même profession',
    ],
    answerIndex: 1,
    source: 'Livret du citoyen',
    page: 5,
  },
  {
    id: 'p-13c26',
    category: 'principes',
    prompt: 'Quelle est la place de la langue française dans la République ?',
    choices: [
      'C\'est la langue officielle de la République',
      'C\'est une langue parmi d\'autres officielles',
      'Elle est facultative',
      'Elle n\'a plus de statut officiel',
    ],
    answerIndex: 0,
    source: 'Constitution de 1958, art. 2',
    page: 4,
  },
  {
    id: 'p-bi9qn',
    category: 'principes',
    prompt: 'Quels sont des symboles officiels de la République française ?',
    choices: [
      'Le coq gaulois exclusivement',
      'La fleur de lys et la couronne',
      'Le drapeau tricolore, La Marseillaise, Marianne et la devise',
      'La tour Eiffel et la baguette',
    ],
    answerIndex: 2,
    source: 'Constitution de 1958, art. 2',
    page: 4,
  },
  {
    id: 'p-c1kog',
    category: 'principes',
    prompt: 'A-t-on le droit d\'insulter publiquement quelqu\'un parce qu\'il est différent (handicap, apparence physique, sexe…) ?',
    choices: [
      'Oui, au nom de la liberté d\'expression',
      'Oui, dans certains cas',
      'Non, c\'est une infraction punie par la loi',
      'Cela dépend de la personne visée',
    ],
    answerIndex: 2,
    source: 'Loi du 29 juillet 1881',
  },
  {
    id: 'p-4n7hu',
    category: 'principes',
    prompt: 'Le régime de la France est :',
    choices: [
      'Une monarchie',
      'Une dictature',
      'Une République démocratique',
      'Une théocratie',
    ],
    answerIndex: 2,
    source: 'Constitution de 1958, art. 1',
  },
  {
    id: 'p-a2vfn',
    category: 'principes',
    prompt: 'Pourquoi le principe de laïcité doit-il être respecté à l\'école ?',
    choices: [
      'Parce que les religions sont interdites en France',
      'Parce que l\'école publique doit être neutre et accueillir tous les enfants quelles que soient leurs convictions',
      'Parce que les enseignants doivent être athées',
      'Parce que c\'est une tradition',
    ],
    answerIndex: 1,
    source: 'Charte de la laïcité à l\'école',
  },
  {
    id: 'p-8u4j3',
    category: 'principes',
    prompt: 'En quelle année la loi de séparation des Églises et de l\'État a-t-elle été votée ?',
    choices: ['1789', '1848', '1905', '1958'],
    answerIndex: 2,
    source: 'Loi du 9 décembre 1905',
    page: 7,
  },
  {
    id: 'p-b2g3j',
    category: 'principes',
    prompt: 'Une personne a-t-elle le droit de ne pas croire en une religion ?',
    choices: [
      'Non, il faut croire à une religion',
      'Oui, c\'est la liberté de conscience',
      'Seulement après 18 ans',
      'Seulement en privé',
    ],
    answerIndex: 1,
    source: 'DDHC 1789, art. 10',
  },
  {
    id: 'p-cto85',
    category: 'principes',
    prompt: 'Quel droit est garanti par la laïcité ?',
    choices: [
      'Le droit d\'imposer sa religion',
      'Le droit de ne pas travailler les jours fériés religieux',
      'La liberté de croire ou de ne pas croire',
      'Le droit de fonder une religion d\'État',
    ],
    answerIndex: 2,
    source: 'Loi de 1905',
  },
  {
    id: 'p-7csbf',
    category: 'principes',
    prompt: 'À l\'école publique, qui peut porter des signes religieux très visibles ?',
    choices: [
      'Les enseignants seulement',
      'Les élèves majeurs seulement',
      'Tout le monde',
      'Personne, c\'est interdit aux élèves comme aux personnels',
    ],
    answerIndex: 3,
    source: 'Loi du 15 mars 2004',
    page: 7,
  },
  {
    id: 'p-cl2e0',
    category: 'principes',
    prompt: 'Selon le principe de laïcité, que signifie la neutralité de l\'État ?',
    choices: [
      'L\'État interdit toutes les religions',
      'L\'État impose une religion à tous',
      'L\'État ne favorise et ne défavorise aucune religion',
      'L\'État finance toutes les religions',
    ],
    answerIndex: 2,
    source: 'Loi de 1905',
  },
  {
    id: 'p-bhicm',
    category: 'principes',
    prompt: 'Que peut faire un usager du service public dans une mairie ?',
    choices: [
      'Imposer ses convictions à l\'agent',
      'Refuser de parler français',
      'Demander un service en respectant les règles, et porter ou non un signe religieux',
      'Ne pas respecter le règlement intérieur',
    ],
    answerIndex: 2,
    source: 'Charte de la laïcité dans les services publics',
  },
  {
    id: 'p-1oor7',
    category: 'principes',
    prompt: 'Qui doit respecter le principe de neutralité religieuse dans une préfecture ?',
    choices: [
      'Les usagers exclusivement',
      'Les agents publics',
      'Les étrangers exclusivement',
      'Personne',
    ],
    answerIndex: 1,
    source: 'Loi de 1905',
  },
  {
    id: 'p-d5gku',
    category: 'principes',
    prompt: 'La laïcité impose-t-elle aux agents publics d\'être neutres vis-à-vis des usagers ?',
    choices: [
      'Non, ils ont la liberté d\'expression',
      'Oui, ils ne doivent pas manifester leurs convictions dans leurs fonctions',
      'Seulement à Paris',
      'Seulement le dimanche',
    ],
    answerIndex: 1,
    source: 'Loi de 1905',
  },
  {
    id: 'p-cigv',
    category: 'principes',
    prompt: 'Que garantit le principe de laïcité ?',
    choices: [
      'L\'interdiction de toutes les religions',
      'Une religion d\'État protégée',
      'La séparation des religions et de l\'État, et la liberté de conscience',
      'La possibilité de ne pas payer d\'impôts',
    ],
    answerIndex: 2,
    source: 'Loi de 1905',
  },
  {
    id: 'p-k6rl',
    category: 'principes',
    prompt: 'A-t-on le droit de changer de religion ?',
    choices: [
      'Non, c\'est interdit',
      'Oui, c\'est un droit garanti par la liberté de conscience',
      'Seulement avec l\'autorisation des parents',
      'Une seule fois dans sa vie',
    ],
    answerIndex: 1,
    source: 'DDHC 1789, art. 10',
  },
  {
    id: 'p-3heb7',
    category: 'principes',
    prompt: 'Que représente la laïcité ?',
    choices: [
      'L\'absence de religion en France',
      'L\'interdiction de toute pratique religieuse',
      'La séparation des religions et de l\'État, et la liberté de croyance',
      'Une religion officielle',
    ],
    answerIndex: 2,
    source: 'Constitution de 1958, art. 1',
  },
  {
    id: 'p-4ra50',
    category: 'principes',
    prompt: 'Qu\'est ce qui est interdit par la Charte de la laïcité à l\'école ?',
    choices: [
      'Étudier les religions en cours',
      'Le port de signes religieux ostensibles et le prosélytisme',
      'Fêter les anniversaires',
      'Avoir une opinion politique',
    ],
    answerIndex: 1,
    source: 'Charte de la laïcité à l\'école',
  },
  {
    id: 'p-bo2e',
    category: 'principes',
    prompt: 'Que dit l\'article 1er de la Constitution française ?',
    choices: [
      'Tous les hommes naissent libres et égaux en droits',
      'La France est une République indivisible, laïque, démocratique et sociale',
      'La souveraineté appartient au peuple',
      'La langue de la République est le français',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958, art. 1',
  },

  // ────────────────────────────────────────────────────────────────────────
  // SYSTÈME INSTITUTIONNEL ET POLITIQUE (50)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: 'i-9fk4a',
    category: 'institutions',
    prompt: 'Qu\'est-ce que l\'État de droit ?',
    choices: [
      'Un État sans police',
      'Un système où chacun, y compris l\'État, est soumis au droit',
      'Un État dirigé uniquement par des juges',
      'Un État qui ne fait pas de lois',
    ],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'i-7a6a3',
    category: 'institutions',
    prompt: 'Le président de la République a commis un crime. Quelle proposition est correcte ?',
    choices: [
      'Il ne peut jamais être jugé',
      'Il peut être destitué par le Parlement réuni en Haute Cour',
      'Il est jugé comme tout citoyen pendant son mandat',
      'Le Premier ministre prend automatiquement sa place',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958, art. 67-68',
  },
  {
    id: 'i-1so34',
    category: 'institutions',
    prompt: 'La loi est l\'expression de :',
    choices: [
      'La volonté du Président',
      'La volonté du Premier ministre',
      'La volonté générale',
      'La volonté du peuple unanime',
    ],
    answerIndex: 2,
    source: 'DDHC 1789, art. 6',
  },
  {
    id: 'i-5op4e',
    category: 'institutions',
    prompt: 'Quelle est la durée du mandat du conseil municipal et du maire ?',
    choices: ['4 ans', '5 ans', '6 ans', '7 ans'],
    answerIndex: 2,
    source: 'Code général des collectivités territoriales',
  },
  {
    id: 'i-98knq',
    category: 'institutions',
    prompt: 'Que garantit l\'État de droit ?',
    choices: [
      'Que personne ne peut être condamné',
      'Que tous, y compris l\'État, sont soumis aux mêmes lois',
      'Que les juges décident seuls de tout',
      'Que les lois changent selon les gouvernants',
    ],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'i-c39rm',
    category: 'institutions',
    prompt: 'Une personne peut-elle voter à la place d\'une autre ?',
    choices: [
      'Oui, dans la même famille',
      'Oui, sans condition',
      'Non, sauf procuration officielle',
      'Seulement entre époux',
    ],
    answerIndex: 2,
    source: 'Code électoral',
  },
  {
    id: 'i-e602o',
    category: 'institutions',
    prompt: 'Est-ce que le vote est obligatoire ?',
    choices: [
      'Oui, sous peine d\'amende',
      'Oui, sous peine de prison',
      'Non, mais il est fortement encouragé',
      'Oui, mais seulement à Paris',
    ],
    answerIndex: 2,
    source: 'Service-public.fr',
  },
  {
    id: 'i-b0j6t',
    category: 'institutions',
    prompt: 'À la fin de son mandat, le président de la République peut-il décider de rester au pouvoir ?',
    choices: [
      'Oui, sans condition',
      'Oui, avec l\'accord du Parlement',
      'Oui, en cas de crise',
      'Non, il doit organiser une élection',
    ],
    answerIndex: 3,
    source: 'Constitution de 1958, art. 6-7',
  },
  {
    id: 'i-3d0kf',
    category: 'institutions',
    prompt: 'Qui dirige l\'action du Gouvernement ?',
    choices: [
      'Le Président de la République',
      'Le Premier ministre',
      'Le président de l\'Assemblée nationale',
      'Le président du Conseil constitutionnel',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958, art. 21',
  },
  {
    id: 'i-a9tvq',
    category: 'institutions',
    prompt: 'Qui nomme le Premier ministre ?',
    choices: [
      'Le peuple par élection directe',
      'Le Président de la République',
      'L\'Assemblée nationale',
      'Le Sénat',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958, art. 8',
  },
  {
    id: 'i-errss',
    category: 'institutions',
    prompt: 'Quelle est l\'organisation administrative de la France ?',
    choices: [
      'Communes uniquement',
      'Provinces et duchés',
      'Communes, départements et régions',
      'Cantons et arrondissements',
    ],
    answerIndex: 2,
    source: 'Livret du citoyen',
  },
  {
    id: 'i-e07gt',
    category: 'institutions',
    prompt: 'Qu\'est-ce que le pouvoir législatif ? Le pouvoir :',
    choices: [
      'De juger les criminels',
      'De faire les lois',
      'De diriger l\'administration',
      'De nommer le Président',
    ],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'i-b482g',
    category: 'institutions',
    prompt: 'Pourquoi séparer les trois pouvoirs dans une démocratie ?',
    choices: [
      'Pour aller plus vite',
      'Pour faire plus de lois',
      'Pour empêcher la concentration du pouvoir et protéger les libertés',
      'Parce que c\'est moins coûteux',
    ],
    answerIndex: 2,
    source: 'Livret du citoyen',
  },
  {
    id: 'i-8lsng',
    category: 'institutions',
    prompt: 'Qui sanctionne l\'auteur d\'un vol ?',
    choices: ['La police', 'La justice (les tribunaux)', 'Le maire', 'Le Président'],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'i-4df52',
    category: 'institutions',
    prompt: 'Quel est le rôle du gouvernement ?',
    choices: [
      'Voter les lois',
      'Déterminer et conduire la politique de la nation',
      'Juger les criminels',
      'Décider seul de la guerre',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958, art. 20',
  },
  {
    id: 'i-er5j8',
    category: 'institutions',
    prompt: 'Que se passe-t-il si un ministre ne respecte pas la loi ?',
    choices: [
      'Il bénéficie d\'une immunité totale',
      'Il peut être jugé comme tout citoyen, devant les tribunaux',
      'Il est destitué automatiquement',
      'Rien, les ministres sont au-dessus des lois',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958, art. 68-1',
  },
  {
    id: 'i-bl50o',
    category: 'institutions',
    prompt: 'Combien de députés composent l\'Assemblée nationale ?',
    choices: ['348', '500', '577', '1000'],
    answerIndex: 2,
    source: 'Code électoral',
  },
  {
    id: 'i-5cpf5',
    category: 'institutions',
    prompt: 'Qui peut voter aux élections en France ?',
    choices: [
      'Tout résident sur le territoire',
      'Les citoyens français majeurs inscrits sur les listes électorales',
      'Les seules personnes nées en France',
      'Toute personne payant des impôts',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958, art. 3',
  },
  {
    id: 'i-fpldv',
    category: 'institutions',
    prompt: 'Pour combien de temps sont élus les sénateurs ?',
    choices: ['4 ans', '5 ans', '6 ans', '9 ans'],
    answerIndex: 2,
    source: 'Constitution de 1958, art. 24',
  },
  {
    id: 'i-e1m2v',
    category: 'institutions',
    prompt: 'La séparation des pouvoirs est un principe fondamental. Quels sont les trois pouvoirs concernés ?',
    choices: [
      'Civil, militaire, religieux',
      'Législatif, exécutif, judiciaire',
      'National, régional, local',
      'Politique, économique, social',
    ],
    answerIndex: 1,
    source: 'DDHC 1789, art. 16',
  },
  {
    id: 'i-2qafg',
    category: 'institutions',
    prompt: 'Est-ce que le président de la République a tous les pouvoirs ?',
    choices: [
      'Oui, il décide de tout',
      'Oui, mais en accord avec son parti',
      'Non, ses pouvoirs sont définis par la Constitution',
      'Oui, pendant 5 ans',
    ],
    answerIndex: 2,
    source: 'Constitution de 1958',
  },
  {
    id: 'i-52cmt',
    category: 'institutions',
    prompt: 'Qui est le préfet ?',
    choices: [
      'Un élu local',
      'Le représentant de l\'État dans le département (et la région)',
      'Le chef de la police nationale',
      'Un magistrat',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958, art. 72',
  },
  {
    id: 'i-fiolm',
    category: 'institutions',
    prompt: 'Quelle condition est nécessaire pour voter aux élections ?',
    choices: [
      'Payer un impôt minimum',
      'Avoir un diplôme',
      'Être citoyen français, majeur, et inscrit sur les listes électorales',
      'Habiter à Paris',
    ],
    answerIndex: 2,
    source: 'Code électoral',
  },
  {
    id: 'i-d5tv5',
    category: 'institutions',
    prompt: 'Qui dirige la commune ?',
    choices: ['Le préfet', 'Le maire, élu par le conseil municipal', 'Le député', 'Le sous-préfet'],
    answerIndex: 1,
    source: 'Code général des collectivités territoriales',
  },
  {
    id: 'i-du82s',
    category: 'institutions',
    prompt: 'Quel est le régime politique de la France aujourd\'hui ?',
    choices: [
      'Une monarchie constitutionnelle',
      'La Cinquième République, un régime semi-présidentiel',
      'Une République parlementaire pure',
      'Un régime présidentiel pur',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958',
  },
  {
    id: 'i-4lv4b',
    category: 'institutions',
    prompt: 'Qu\'est-ce que l\'Hôtel de Matignon ?',
    choices: [
      'La résidence du Président',
      'La résidence et les bureaux du Premier ministre',
      'Le siège de l\'Assemblée nationale',
      'Le siège du Conseil constitutionnel',
    ],
    answerIndex: 1,
    source: 'Service-public.fr',
  },
  {
    id: 'i-727g6',
    category: 'institutions',
    prompt: 'Le Parlement est composé :',
    choices: [
      'De l\'Assemblée nationale uniquement',
      'Du Sénat uniquement',
      'De l\'Assemblée nationale et du Sénat',
      'Du gouvernement et de l\'Assemblée',
    ],
    answerIndex: 2,
    source: 'Constitution de 1958, art. 24',
  },
  {
    id: 'i-fcmqf',
    category: 'institutions',
    prompt: 'Quel est le rôle du président de la République ?',
    choices: [
      'Voter les lois',
      'Garant de la Constitution, chef des armées, il veille à l\'indépendance nationale',
      'Juger les criminels',
      'Diriger les communes',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958, art. 5',
  },
  {
    id: 'i-es44t',
    category: 'institutions',
    prompt: 'Quel est le rôle du Premier ministre ?',
    choices: [
      'Voter les lois',
      'Diriger l\'action du Gouvernement et appliquer les lois',
      'Représenter la France à l\'étranger',
      'Présider le Sénat',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958, art. 21',
  },
  {
    id: 'i-bcbov',
    category: 'institutions',
    prompt: 'Qui est le chef du Gouvernement ?',
    choices: [
      'Le Président de la République',
      'Le Premier ministre',
      'Le président du Sénat',
      'Le ministre de l\'Intérieur',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958, art. 21',
  },
  {
    id: 'i-91e8c',
    category: 'institutions',
    prompt: 'Combien y a-t-il de régions en France ?',
    choices: ['10', '13', '18', '27'],
    answerIndex: 2,
    source: 'Service-public.fr',
    explanation: '13 régions en métropole et 5 en outre-mer, soit 18 au total.',
  },
  {
    id: 'i-aqgml',
    category: 'institutions',
    prompt: 'Quel est le rôle du Défenseur des droits ?',
    choices: [
      'Diriger l\'armée',
      'Présider l\'Assemblée nationale',
      'Veiller au respect des droits et libertés des personnes',
      'Nommer les juges',
    ],
    answerIndex: 2,
    source: 'Constitution de 1958, art. 71-1',
  },
  {
    id: 'i-8iln',
    category: 'institutions',
    prompt: 'Depuis quand l\'euro est-elle la monnaie unique ?',
    choices: ['1992', '1999', '2002', '2007'],
    answerIndex: 2,
    source: 'Banque centrale européenne',
    explanation: 'L\'euro est devenu la monnaie en pièces et billets utilisée par les citoyens en 2002 (1999 pour les transactions scripturales).',
  },
  {
    id: 'i-c6h4k',
    category: 'institutions',
    prompt: 'Quel est le rôle principal du département ?',
    choices: [
      'La défense nationale',
      'L\'action sociale (RSA, aide à l\'enfance) et la gestion des collèges',
      'La gestion des écoles maternelles',
      'Le maintien de l\'ordre public',
    ],
    answerIndex: 1,
    source: 'Service-public.fr',
  },
  {
    id: 'i-6k6s2',
    category: 'institutions',
    prompt: 'Quel est le rôle principal des communes ?',
    choices: [
      'Faire les lois',
      'Gérer la vie locale (état civil, écoles primaires, urbanisme)',
      'Diriger l\'armée',
      'Gérer les hôpitaux',
    ],
    answerIndex: 1,
    source: 'Service-public.fr',
  },
  {
    id: 'i-677k4',
    category: 'institutions',
    prompt: 'Combien de communes environ existe-t-il en France ?',
    choices: ['1 000', '10 000', '35 000', '100 000'],
    answerIndex: 2,
    source: 'INSEE',
  },
  {
    id: 'i-gid9',
    category: 'institutions',
    prompt: 'Quel traité concerne la construction de l\'Union européenne ?',
    choices: [
      'Le traité de Versailles',
      'Le traité de Maastricht',
      'Le traité d\'Aix-la-Chapelle',
      'Le traité de Yalta',
    ],
    answerIndex: 1,
    source: 'Traité de Maastricht (1992)',
  },
  {
    id: 'i-5nb17',
    category: 'institutions',
    prompt: 'Quel État a quitté l\'Union européenne en 2020 ?',
    choices: ['La Suisse', 'Le Royaume-Uni', 'La Norvège', 'La Turquie'],
    answerIndex: 1,
    source: 'Brexit (2020)',
  },
  {
    id: 'i-2h28v',
    category: 'institutions',
    prompt: 'Quelle est la devise de l\'Union européenne ?',
    choices: [
      'Liberté, égalité, fraternité',
      'Unie dans la diversité',
      'Paix et progrès',
      'Un pour tous, tous pour un',
    ],
    answerIndex: 1,
    source: 'europa.eu',
  },
  {
    id: 'i-5g8q',
    category: 'institutions',
    prompt: 'Quel est l\'hymne de l\'Union européenne ?',
    choices: [
      'La Marseillaise',
      'L\'Ode à la joie (de Beethoven)',
      'God Save the King',
      'L\'Internationale',
    ],
    answerIndex: 1,
    source: 'europa.eu',
  },
  {
    id: 'i-9lvot',
    category: 'institutions',
    prompt: 'De quoi est composé le drapeau européen ?',
    choices: [
      '12 étoiles dorées sur fond bleu',
      '27 étoiles dorées sur fond bleu',
      '50 étoiles blanches sur fond bleu',
      'Un cercle d\'étoiles avec une croix',
    ],
    answerIndex: 0,
    source: 'europa.eu',
  },
  {
    id: 'i-bcc9b',
    category: 'institutions',
    prompt: 'De quelle couleur est le drapeau européen ?',
    choices: ['Vert', 'Rouge', 'Bleu', 'Blanc'],
    answerIndex: 2,
    source: 'europa.eu',
  },
  {
    id: 'i-11t9i',
    category: 'institutions',
    prompt: 'En quelle année le traité de Maastricht, qui marque la fondation de l\'Union européenne, a-t-il été signé ?',
    choices: ['1957', '1986', '1992', '2007'],
    answerIndex: 2,
    source: 'Traité de Maastricht',
  },
  {
    id: 'i-aud95',
    category: 'institutions',
    prompt: 'Où est le siège du Parlement européen ?',
    choices: ['Bruxelles', 'Luxembourg', 'Strasbourg', 'Berlin'],
    answerIndex: 2,
    source: 'europa.eu',
  },
  {
    id: 'i-43mg0',
    category: 'institutions',
    prompt: 'Où est le siège de la Commission européenne ?',
    choices: ['Strasbourg', 'Bruxelles', 'Francfort', 'Luxembourg'],
    answerIndex: 1,
    source: 'europa.eu',
  },
  {
    id: 'i-bokkq',
    category: 'institutions',
    prompt: 'Quel État n\'est pas membre de l\'Union européenne ?',
    choices: ['La France', 'L\'Allemagne', 'La Suisse', 'L\'Italie'],
    answerIndex: 2,
    source: 'europa.eu',
  },
  {
    id: 'i-1nm24',
    category: 'institutions',
    prompt: 'Quand célèbre-t-on la journée de l\'Europe ?',
    choices: ['Le 1er mai', 'Le 8 mai', 'Le 9 mai', 'Le 14 juillet'],
    answerIndex: 2,
    source: 'europa.eu',
  },
  {
    id: 'i-8hj6',
    category: 'institutions',
    prompt: 'À quelle fréquence les élections européennes sont-elles organisées ?',
    choices: ['Tous les 4 ans', 'Tous les 5 ans', 'Tous les 6 ans', 'Tous les 7 ans'],
    answerIndex: 1,
    source: 'europa.eu',
  },
  {
    id: 'i-1eoc6',
    category: 'institutions',
    prompt: 'Quelle condition est nécessaire pour voter aux élections européennes ?',
    choices: [
      'Être seulement français',
      'Être citoyen d\'un État membre de l\'UE, majeur et inscrit sur les listes électorales',
      'Habiter en France depuis 10 ans',
      'Avoir un diplôme',
    ],
    answerIndex: 1,
    source: 'Code électoral',
  },
  {
    id: 'i-d86bd',
    category: 'institutions',
    prompt: 'Quel pays est un pays fondateur de l\'Union européenne ?',
    choices: ['La France', 'Le Royaume-Uni', 'L\'Espagne', 'La Suède'],
    answerIndex: 0,
    source: 'Traité de Rome (1957)',
  },

  // ────────────────────────────────────────────────────────────────────────
  // DROITS ET DEVOIRS (38)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: 'd-ab547',
    category: 'droits',
    prompt: 'À quelle liberté la PMA fait-elle référence ?',
    choices: [
      'La liberté d\'expression',
      'La liberté individuelle (droit de fonder une famille)',
      'La liberté religieuse',
      'La liberté d\'association',
    ],
    answerIndex: 1,
    source: 'Loi de bioéthique du 2 août 2021',
  },
  {
    id: 'd-cv6u6',
    category: 'droits',
    prompt: 'Au nom de quoi l\'État justifie-t-il la restriction des droits ?',
    choices: [
      'Du secret défense',
      'De la volonté du Président',
      'De l\'intérêt général et de la protection de l\'ordre public',
      'Des intérêts économiques privés',
    ],
    answerIndex: 2,
    source: 'DDHC 1789, art. 4',
  },
  {
    id: 'd-eeltm',
    category: 'droits',
    prompt: 'Concernant le droit de se marier, quelle proposition est correcte ?',
    choices: [
      'Le mariage est interdit aux étrangers',
      'Toute personne majeure peut se marier librement avec la personne de son choix',
      'Il faut obligatoirement l\'accord du préfet',
      'Le mariage est réservé aux Français',
    ],
    answerIndex: 1,
    source: 'Code civil',
  },
  {
    id: 'd-96mht',
    category: 'droits',
    prompt: 'Est-il toujours possible de divorcer ?',
    choices: [
      'Non, il faut une raison grave',
      'Oui, le divorce est un droit',
      'Seulement après 10 ans de mariage',
      'Seulement avec l\'accord des parents',
    ],
    answerIndex: 1,
    source: 'Code civil',
  },
  {
    id: 'd-2sskc',
    category: 'droits',
    prompt: 'La peine de mort est :',
    choices: [
      'En vigueur pour les crimes graves',
      'Suspendue mais légale',
      'Abolie en France depuis 1981',
      'Réservée aux crimes contre l\'État',
    ],
    answerIndex: 2,
    source: 'Loi du 9 octobre 1981',
  },
  {
    id: 'd-5g7bj',
    category: 'droits',
    prompt: 'Laquelle de ces citations est inscrite dans la Déclaration des Droits de l\'homme et du Citoyen de 1789 ?',
    choices: [
      '« Liberté, Égalité, Fraternité »',
      '« Les hommes naissent et demeurent libres et égaux en droits »',
      '« L\'État, c\'est moi »',
      '« Le travail rend libre »',
    ],
    answerIndex: 1,
    source: 'DDHC 1789, art. 1',
  },
  {
    id: 'd-du7gl',
    category: 'droits',
    prompt: 'Le recours à l\'avortement est-il autorisé ?',
    choices: [
      'Non, c\'est interdit',
      'Oui, c\'est un droit (IVG)',
      'Seulement en cas de viol',
      'Seulement avec l\'accord des parents',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958, art. 34 (rév. 2024)',
  },
  {
    id: 'd-5ipuj',
    category: 'droits',
    prompt: 'Que contient la Constitution ?',
    choices: [
      'Le code de la route',
      'Les règles fondamentales d\'organisation de l\'État et les droits fondamentaux',
      'Les peines pour les crimes',
      'Les règles fiscales',
    ],
    answerIndex: 1,
    source: 'Constitution de 1958',
  },
  {
    id: 'd-6fi5j',
    category: 'droits',
    prompt: 'Que garantit la liberté de la presse ?',
    choices: [
      'Le droit de mentir publiquement',
      'Le droit d\'informer, d\'enquêter et de critiquer dans le respect de la loi',
      'L\'obligation pour l\'État de financer les médias',
      'La gratuité des journaux',
    ],
    answerIndex: 1,
    source: 'Loi du 29 juillet 1881',
  },
  {
    id: 'd-8jrm5',
    category: 'droits',
    prompt: 'Que prévoit la Charte de l\'environnement ?',
    choices: [
      'L\'interdiction des énergies fossiles',
      'Le droit de chacun à un environnement sain et le devoir de le préserver',
      'L\'obligation d\'être végétarien',
      'La création d\'un ministère unique',
    ],
    answerIndex: 1,
    source: 'Charte de l\'environnement (2005)',
  },
  {
    id: 'd-2u6fk',
    category: 'droits',
    prompt: 'Que signifie la dignité humaine ?',
    choices: [
      'Le respect dû à toute personne en tant qu\'être humain',
      'Le droit d\'avoir un travail',
      'Le droit de voter',
      'Le devoir de saluer son chef',
    ],
    answerIndex: 0,
    source: 'Préambule Constitution 1946',
  },
  {
    id: 'd-502q8',
    category: 'droits',
    prompt: 'Que signifie le droit de manifester ?',
    choices: [
      'Le droit de bloquer la circulation sans déclaration',
      'Le droit de s\'exprimer publiquement et collectivement, sous certaines conditions',
      'Le droit d\'occuper toute propriété privée',
      'Le droit d\'agresser des contre-manifestants',
    ],
    answerIndex: 1,
    source: 'Service-public.fr',
  },
  {
    id: 'd-3dfhh',
    category: 'droits',
    prompt: 'Que signifie PMA ?',
    choices: [
      'Procréation médicalement assistée',
      'Protection médicale ambulatoire',
      'Programme médical adulte',
      'Plan médical d\'avenir',
    ],
    answerIndex: 0,
    source: 'Service-public.fr',
  },
  {
    id: 'd-7mre',
    category: 'droits',
    prompt: 'Quel texte est le plus difficile à modifier ?',
    choices: ['Une loi ordinaire', 'Un décret', 'La Constitution', 'Une circulaire'],
    answerIndex: 2,
    source: 'Constitution de 1958, art. 89',
  },
  {
    id: 'd-2d3pl',
    category: 'droits',
    prompt: 'Quelle liberté permet à une personne de croire en la religion de son choix ?',
    choices: [
      'La liberté d\'expression',
      'La liberté de conscience (et de religion)',
      'La liberté d\'association',
      'La liberté de circulation',
    ],
    answerIndex: 1,
    source: 'DDHC 1789, art. 10',
  },
  {
    id: 'd-7pea1',
    category: 'droits',
    prompt: 'Qu\'est-ce que le droit de grève ?',
    choices: [
      'Le droit de ne pas aller travailler quand on veut',
      'Le droit pour les salariés de cesser collectivement le travail pour défendre leurs revendications',
      'Le droit de bloquer son entreprise',
      'Le droit de démissionner sans préavis',
    ],
    answerIndex: 1,
    source: 'Préambule Constitution 1946',
  },
  {
    id: 'd-b95kp',
    category: 'droits',
    prompt: 'Qu\'est-ce que la Constitution ?',
    choices: [
      'La loi fondamentale qui organise l\'État et garantit les droits',
      'Une loi votée chaque année',
      'Un décret du Président',
      'Le règlement intérieur de l\'Assemblée',
    ],
    answerIndex: 0,
    source: 'Constitution de 1958',
  },
  {
    id: 'd-980is',
    category: 'droits',
    prompt: 'Qui peut demander à avorter ?',
    choices: [
      'Toute femme enceinte qui ne souhaite pas poursuivre sa grossesse, dans les délais légaux',
      'Seulement les femmes mariées',
      'Seulement avec l\'accord du conjoint',
      'Seulement avec l\'accord des parents',
    ],
    answerIndex: 0,
    source: 'Code de la santé publique',
  },
  {
    id: 'd-9oq3q',
    category: 'droits',
    prompt: 'Une femme majeure de nationalité française a-t-elle le droit de voter aux élections ?',
    choices: [
      'Non',
      'Oui, depuis 1944',
      'Seulement aux élections municipales',
      'Seulement avec l\'accord du conjoint',
    ],
    answerIndex: 1,
    source: 'Ordonnance du 21 avril 1944',
  },
  {
    id: 'd-3nvsb',
    category: 'droits',
    prompt: 'Concernant l\'utilisation des réseaux sociaux, quelle proposition est correcte ?',
    choices: [
      'Tout est permis sur les réseaux sociaux',
      'Les réseaux sociaux sont une zone de non-droit',
      'La loi s\'applique aussi en ligne (insultes, menaces, diffamation sont punies)',
      'Seuls les contenus politiques sont régulés',
    ],
    answerIndex: 2,
    source: 'Code pénal',
  },
  {
    id: 'd-d0ncd',
    category: 'droits',
    prompt: 'Jeter un mégot par terre est :',
    choices: [
      'Autorisé',
      'Interdit et puni d\'une amende',
      'Interdit seulement à Paris',
      'Toléré près des poubelles',
    ],
    answerIndex: 1,
    source: 'Code de l\'environnement',
  },
  {
    id: 'd-2pvcr',
    category: 'droits',
    prompt: 'L\'État peut-il limiter les droits et libertés ?',
    choices: [
      'Non, jamais',
      'Oui, sans condition',
      'Oui, par la loi et au nom de l\'intérêt général',
      'Seulement en temps de guerre',
    ],
    answerIndex: 2,
    source: 'DDHC 1789, art. 4',
  },
  {
    id: 'd-52a2b',
    category: 'droits',
    prompt: 'Parmi ces actions, laquelle permet d\'adopter une attitude respectueuse de l\'environnement ?',
    choices: [
      'Brûler ses déchets dans son jardin',
      'Trier ses déchets et économiser l\'eau',
      'Laisser les robinets ouverts',
      'Utiliser des sacs plastiques à usage unique',
    ],
    answerIndex: 1,
    source: 'Charte de l\'environnement',
  },
  {
    id: 'd-85l16',
    category: 'droits',
    prompt: 'Quelle proposition constitue une obligation ?',
    choices: [
      'Voter à toutes les élections',
      'Adhérer à un parti politique',
      'Respecter la loi et payer ses impôts',
      'Pratiquer une religion',
    ],
    answerIndex: 2,
    source: 'Charte des droits et devoirs',
  },
  {
    id: 'd-3hk6t',
    category: 'droits',
    prompt: 'Pour quel motif peut-on limiter la liberté d\'expression ?',
    choices: [
      'Pour protéger les opinions du gouvernement',
      'Pour empêcher la critique des institutions',
      'Pour protéger l\'ordre public et la dignité d\'autrui',
      'Pour favoriser une religion',
    ],
    answerIndex: 2,
    source: 'Loi du 29 juillet 1881',
  },
  {
    id: 'd-6veln',
    category: 'droits',
    prompt: 'Pourquoi doit-on trier ses déchets ?',
    choices: [
      'Pour permettre leur recyclage et protéger l\'environnement',
      'Pour réduire les impôts',
      'Pour respecter une superstition',
      'C\'est facultatif',
    ],
    answerIndex: 0,
    source: 'Code de l\'environnement',
  },
  {
    id: 'd-ci9rj',
    category: 'droits',
    prompt: 'Que doit faire une victime de violences ?',
    choices: [
      'Se venger elle-même',
      'Porter plainte (police, gendarmerie ou tribunal) et chercher de l\'aide',
      'Cacher les faits',
      'Régler le conflit en privé',
    ],
    answerIndex: 1,
    source: 'Service-public.fr',
  },
  {
    id: 'd-76hhf',
    category: 'droits',
    prompt: 'Que doit-on faire face aux ordres des policiers ou gendarmes ?',
    choices: [
      'Les ignorer',
      'S\'enfuir si on n\'est pas d\'accord',
      'Les respecter, dans le cadre de la loi',
      'Refuser systématiquement',
    ],
    answerIndex: 2,
    source: 'Code pénal',
  },
  {
    id: 'd-jbk2',
    category: 'droits',
    prompt: 'Quel est le rôle de la police ?',
    choices: [
      'Voter les lois',
      'Faire respecter la loi, protéger les personnes et les biens',
      'Juger les criminels',
      'Diriger les écoles',
    ],
    answerIndex: 1,
    source: 'Code de la sécurité intérieure',
  },
  {
    id: 'd-dpiej',
    category: 'droits',
    prompt: 'Quel est un exemple d\'assistance à personne en danger ?',
    choices: [
      'Filmer la scène pour la diffuser',
      'Appeler les secours quand on voit une personne blessée',
      'Passer son chemin',
      'Voler les affaires de la victime',
    ],
    answerIndex: 1,
    source: 'Code pénal, art. 223-6',
  },
  {
    id: 'd-2rm9a',
    category: 'droits',
    prompt: 'Quel exemple illustre une limitation de liberté pour protéger l\'intérêt général ?',
    choices: [
      'Le port obligatoire de la ceinture de sécurité',
      'L\'obligation de voter pour un parti unique',
      'L\'interdiction des associations',
      'L\'obligation de pratiquer une religion',
    ],
    answerIndex: 0,
    source: 'Code de la route',
  },
  {
    id: 'd-8r55i',
    category: 'droits',
    prompt: 'Quelle est l\'attitude à avoir lorsque qu\'on est témoin de violences ?',
    choices: [
      'Filmer et publier sur internet',
      'Alerter les secours ou la police, sans se mettre en danger',
      'Ignorer la situation',
      'Intervenir physiquement seul',
    ],
    answerIndex: 1,
    source: 'Code pénal, art. 223-6',
  },
  {
    id: 'd-5db46',
    category: 'droits',
    prompt: 'Quelle est l\'infraction la plus grave ?',
    choices: ['La contravention', 'Le délit', 'Le crime', 'Le manquement administratif'],
    answerIndex: 2,
    source: 'Code pénal',
  },
  {
    id: 'd-b94mr',
    category: 'droits',
    prompt: 'Quelle obligation concerne toutes les personnes résidant en France quelle que soit leur nationalité ?',
    choices: [
      'Voter aux élections',
      'Servir dans l\'armée française',
      'Respecter la loi française et payer les impôts dus',
      'Pratiquer le français au quotidien',
    ],
    answerIndex: 2,
    source: 'Charte des droits et devoirs',
  },
  {
    id: 'd-7hfhj',
    category: 'droits',
    prompt: 'Quelle proposition représente un exemple de crime ?',
    choices: [
      'Un excès de vitesse',
      'Un vol simple à l\'étalage',
      'Le meurtre',
      'Un défaut de paiement',
    ],
    answerIndex: 2,
    source: 'Code pénal',
  },
  {
    id: 'd-2k5st',
    category: 'droits',
    prompt: 'Quelle proposition représente un exemple de délit ?',
    choices: [
      'Un meurtre',
      'Un excès de vitesse mineur',
      'Le vol',
      'Une discussion bruyante',
    ],
    answerIndex: 2,
    source: 'Code pénal',
  },
  {
    id: 'd-d3j39',
    category: 'droits',
    prompt: 'Qui veille au maintien de l\'ordre public ?',
    choices: [
      'Le maire seul',
      'La police et la gendarmerie',
      'Les pompiers',
      'L\'armée régulièrement',
    ],
    answerIndex: 1,
    source: 'Code de la sécurité intérieure',
  },
  {
    id: 'd-9hone',
    category: 'droits',
    prompt: 'S\'agissant des déchets, quelle proposition est correcte ?',
    choices: [
      'On peut les jeter n\'importe où',
      'Il faut les trier selon les consignes de la commune',
      'On doit tous les brûler',
      'Seuls les déchets dangereux sont triés',
    ],
    answerIndex: 1,
    source: 'Code de l\'environnement',
  },

  // ────────────────────────────────────────────────────────────────────────
  // HISTOIRE, GÉOGRAPHIE ET CULTURE (49)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: 'h-21m3c',
    category: 'histoire',
    prompt: 'Quel était le surnom de Louis XIV ?',
    choices: ['Le Bien-Aimé', 'Le Roi-Soleil', 'Saint Louis', 'Le Conquérant'],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-otcp',
    category: 'histoire',
    prompt: 'Quel roi de France a été exécuté pendant la Révolution française ?',
    choices: ['Louis XIV', 'Louis XV', 'Louis XVI', 'Charles X'],
    answerIndex: 2,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-cj12c',
    category: 'histoire',
    prompt: 'En quelle année Napoléon Ier est-il devenu empereur ?',
    choices: ['1789', '1799', '1804', '1815'],
    answerIndex: 2,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-cgu0f',
    category: 'histoire',
    prompt: 'Lequel de ces personnages a un lien avec la République française ?',
    choices: ['Marianne', 'Louis XIV', 'Napoléon III', 'François Ier'],
    answerIndex: 0,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-3cn11',
    category: 'histoire',
    prompt: 'De quand date l\'appel à la résistance du général de Gaulle ?',
    choices: ['18 juin 1940', '14 juillet 1940', '8 mai 1945', '11 novembre 1918'],
    answerIndex: 0,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-2hjof',
    category: 'histoire',
    prompt: 'Pourquoi la Shoah est-elle étudiée à l\'école ?',
    choices: [
      'Parce que c\'est un événement français',
      'Pour préserver la mémoire et lutter contre toute forme de haine',
      'Pour glorifier les vainqueurs',
      'Parce que c\'est une obligation religieuse',
    ],
    answerIndex: 1,
    source: 'Programmes scolaires — Éducation nationale',
  },
  {
    id: 'h-60v0j',
    category: 'histoire',
    prompt: 'Quel pays a été colonisé par la France ?',
    choices: ['La Suisse', 'L\'Italie', 'L\'Algérie', 'La Norvège'],
    answerIndex: 2,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-8lqkq',
    category: 'histoire',
    prompt: 'Depuis quand les Français élisent-ils le président de la République au suffrage universel direct ?',
    choices: ['1944', '1958', '1962', '1981'],
    answerIndex: 2,
    source: 'Référendum de 1962',
  },
  {
    id: 'h-3j3if',
    category: 'histoire',
    prompt: 'Quelle est la première étape de la construction européenne en 1951 ?',
    choices: [
      'L\'Union européenne',
      'L\'OTAN',
      'La Communauté européenne du charbon et de l\'acier (CECA)',
      'La Communauté économique européenne',
    ],
    answerIndex: 2,
    source: 'Traité de Paris (1951)',
  },
  {
    id: 'h-cv13m',
    category: 'histoire',
    prompt: 'Durant le mandat de quel président la peine de mort a-t-elle été abolie ?',
    choices: [
      'Charles de Gaulle',
      'Valéry Giscard d\'Estaing',
      'François Mitterrand',
      'Jacques Chirac',
    ],
    answerIndex: 2,
    source: 'Loi du 9 octobre 1981',
  },
  {
    id: 'h-fu098',
    category: 'histoire',
    prompt: 'Quel régime politique a été mis en place pendant la Révolution française en 1792 ?',
    choices: [
      'La monarchie constitutionnelle',
      'La Première République',
      'L\'Empire',
      'La Restauration',
    ],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-17gnb',
    category: 'histoire',
    prompt: 'Qui était une figure de la Résistance française pendant la Seconde Guerre mondiale ?',
    choices: ['Jean Moulin', 'Louis XVI', 'Napoléon III', 'Maréchal Pétain'],
    answerIndex: 0,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-cmk36',
    category: 'histoire',
    prompt: 'En 1944, qu\'est-ce qui a changé pour les femmes ?',
    choices: [
      'Le droit de travailler',
      'Le droit d\'étudier',
      'Elles ont obtenu le droit de vote',
      'Le droit de divorcer',
    ],
    answerIndex: 2,
    source: 'Ordonnance du 21 avril 1944',
  },
  {
    id: 'h-a441c',
    category: 'histoire',
    prompt: 'Quelle organisation internationale a été créée en 1945 après la Seconde Guerre mondiale ?',
    choices: [
      'L\'OTAN',
      'L\'Union européenne',
      'L\'ONU (Organisation des Nations unies)',
      'La Société des Nations',
    ],
    answerIndex: 2,
    source: 'Charte des Nations unies (1945)',
  },
  {
    id: 'h-3lr1c',
    category: 'histoire',
    prompt: 'Quelle peine a été supprimée en 1981 ?',
    choices: [
      'La prison à vie',
      'Les travaux forcés',
      'La peine de mort',
      'La déchéance de nationalité',
    ],
    answerIndex: 2,
    source: 'Loi du 9 octobre 1981',
  },
  {
    id: 'h-4b1mk',
    category: 'histoire',
    prompt: 'En quelle année l\'euro est-elle devenue la monnaie utilisée en France ?',
    choices: ['1992', '1999', '2002', '2004'],
    answerIndex: 2,
    source: 'Banque de France',
  },
  {
    id: 'h-3iq21',
    category: 'histoire',
    prompt: 'En quelle année a commencé la Première Guerre mondiale ?',
    choices: ['1870', '1914', '1918', '1939'],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-drapl',
    category: 'histoire',
    prompt: 'Où a eu lieu le débarquement en 1944 ?',
    choices: ['En Bretagne', 'En Normandie', 'Sur la Côte d\'Azur', 'Dans le Pas-de-Calais'],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-2242t',
    category: 'histoire',
    prompt: 'Quel continent a été le plus concerné par la décolonisation française après la Seconde Guerre mondiale ?',
    choices: ['L\'Europe', 'L\'Afrique', 'L\'Amérique', 'L\'Océanie'],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-fvggk',
    category: 'histoire',
    prompt: 'Que fête-t-on le 8 mai ?',
    choices: [
      'La fête nationale',
      'La victoire alliée de 1945 (fin de la Seconde Guerre mondiale en Europe)',
      'L\'armistice de 1918',
      'La prise de la Bastille',
    ],
    answerIndex: 1,
    source: 'Service-public.fr',
  },
  {
    id: 'h-551lm',
    category: 'histoire',
    prompt: 'Quelle mer ou océan borde la France métropolitaine ?',
    choices: ['La mer Caspienne', 'La mer du Japon', 'L\'océan Atlantique', 'La mer Rouge'],
    answerIndex: 2,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-1qm0h',
    category: 'histoire',
    prompt: 'Quel pays a une frontière terrestre avec la France métropolitaine ?',
    choices: ['L\'Espagne', 'La Pologne', 'Le Portugal', 'L\'Autriche'],
    answerIndex: 0,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-esa8u',
    category: 'histoire',
    prompt: 'Quelle ville française est un port maritime ?',
    choices: ['Lyon', 'Marseille', 'Paris', 'Toulouse'],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-6fl7e',
    category: 'histoire',
    prompt: 'Quelle mer se situe entre la France et l\'Angleterre ?',
    choices: [
      'La mer Méditerranée',
      'La Manche',
      'La mer du Nord',
      'L\'océan Atlantique',
    ],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-aiptu',
    category: 'histoire',
    prompt: 'Qu\'est ce que la France d\'outre-mer ?',
    choices: [
      'L\'ensemble des territoires français situés hors d\'Europe',
      'Une ancienne colonie',
      'Une partie de la métropole',
      'Un département de l\'UE',
    ],
    answerIndex: 0,
    source: 'Service-public.fr',
  },
  {
    id: 'h-67m56',
    category: 'histoire',
    prompt: 'Quelle chaîne de montagnes est située entre la France et l\'Espagne ?',
    choices: ['Les Alpes', 'Les Pyrénées', 'Le Jura', 'Les Vosges'],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-11tpm',
    category: 'histoire',
    prompt: 'Quelle île française se trouve dans l\'océan Indien ?',
    choices: ['La Corse', 'La Martinique', 'La Réunion', 'La Guadeloupe'],
    answerIndex: 2,
    source: 'Service-public.fr',
  },
  {
    id: 'h-4h1l3',
    category: 'histoire',
    prompt: 'Quelle est la population approximative de la France en 2025 ?',
    choices: [
      '50 millions d\'habitants',
      '68 millions d\'habitants',
      '80 millions d\'habitants',
      '100 millions d\'habitants',
    ],
    answerIndex: 1,
    source: 'INSEE',
  },
  {
    id: 'h-ejju4',
    category: 'histoire',
    prompt: 'Quel fleuve traverse Paris ?',
    choices: ['La Loire', 'La Seine', 'Le Rhône', 'La Garonne'],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-654r5',
    category: 'histoire',
    prompt: 'Lequel de ces pays partage des frontières terrestres avec la France ?',
    choices: ['Le Royaume-Uni', 'L\'Allemagne', 'La Pologne', 'La Suède'],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-f6j6o',
    category: 'histoire',
    prompt: 'Quel pays a une frontière avec la France métropolitaine au nord-est ?',
    choices: ['L\'Espagne', 'L\'Allemagne', 'L\'Italie', 'Le Royaume-Uni'],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-aprfd',
    category: 'histoire',
    prompt: 'Où se trouvent les principales activités économiques en France ?',
    choices: [
      'Dans les zones rurales isolées',
      'Dans les grandes métropoles (Paris, Lyon, Marseille…)',
      'Uniquement en outre-mer',
      'Sur la côte normande exclusivement',
    ],
    answerIndex: 1,
    source: 'INSEE',
  },
  {
    id: 'h-eh37m',
    category: 'histoire',
    prompt: 'Parmi ces pays, lequel attire le plus de visiteurs chaque année ?',
    choices: ['La France', 'La Belgique', 'Le Portugal', 'L\'Autriche'],
    answerIndex: 0,
    source: 'Atout France',
  },
  {
    id: 'h-2qr9o',
    category: 'histoire',
    prompt: 'Où habite la majorité des Français ?',
    choices: ['À la campagne', 'En ville (en zone urbaine)', 'En montagne', 'À l\'étranger'],
    answerIndex: 1,
    source: 'INSEE',
  },
  {
    id: 'h-aee63',
    category: 'histoire',
    prompt: 'Quelle région est la plus peuplée ?',
    choices: [
      'L\'Auvergne-Rhône-Alpes',
      'L\'Île-de-France',
      'La Provence-Alpes-Côte d\'Azur',
      'La Bretagne',
    ],
    answerIndex: 1,
    source: 'INSEE',
  },
  {
    id: 'h-cbj5e',
    category: 'histoire',
    prompt: 'Quelle ville française fait partie des 10 plus grandes métropoles du pays ?',
    choices: ['Lyon', 'Reims', 'Tours', 'Limoges'],
    answerIndex: 0,
    source: 'INSEE',
  },
  {
    id: 'h-95d74',
    category: 'histoire',
    prompt: 'Lequel de ces départements de France est le plus touristique ?',
    choices: ['Paris (75)', 'La Creuse (23)', 'Le Cantal (15)', 'La Lozère (48)'],
    answerIndex: 0,
    source: 'Atout France',
  },
  {
    id: 'h-5f2pq',
    category: 'histoire',
    prompt: 'Quand peut-on visiter gratuitement des lieux culturels en France ?',
    choices: [
      'Tous les jours',
      'Lors des Journées européennes du patrimoine et le 1er dimanche de chaque mois pour de nombreux musées',
      'Le 14 juillet uniquement',
      'Jamais',
    ],
    answerIndex: 1,
    source: 'Ministère de la Culture',
  },
  {
    id: 'h-5m782',
    category: 'histoire',
    prompt: 'Combien de personnes parlent français dans le monde ?',
    choices: [
      '50 millions',
      '100 millions',
      'Environ 320 millions',
      '1 milliard',
    ],
    answerIndex: 2,
    source: 'Organisation internationale de la Francophonie',
  },
  {
    id: 'h-7jufd',
    category: 'histoire',
    prompt: 'Qui était Marguerite Yourcenar ?',
    choices: [
      'Une chanteuse',
      'Une écrivaine française, première femme élue à l\'Académie française',
      'Une scientifique',
      'Une exploratrice',
    ],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-8t8mh',
    category: 'histoire',
    prompt: 'Quel peintre est français ?',
    choices: [
      'Pablo Picasso',
      'Vincent Van Gogh',
      'Claude Monet',
      'Léonard de Vinci',
    ],
    answerIndex: 2,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-evnt2',
    category: 'histoire',
    prompt: 'Quel musée est situé à Paris ?',
    choices: ['Le Prado', 'Les Offices', 'Le Louvre', 'Le British Museum'],
    answerIndex: 2,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-76ms8',
    category: 'histoire',
    prompt: 'Qui était Auguste Rodin ?',
    choices: [
      'Un peintre belge',
      'Un sculpteur français',
      'Un compositeur italien',
      'Un architecte allemand',
    ],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-3tdll',
    category: 'histoire',
    prompt: 'Quel est le classement de la langue française parmi les langues les plus parlées dans le monde ?',
    choices: [
      '1re',
      'Elle figure parmi les 5 premières langues les plus parlées',
      '10e',
      '20e',
    ],
    answerIndex: 1,
    source: 'OIF',
  },
  {
    id: 'h-9ol9f',
    category: 'histoire',
    prompt: 'Quelle cathédrale célèbre a été en partie détruite par un incendie en 2019 ?',
    choices: [
      'La cathédrale de Reims',
      'Notre-Dame de Paris',
      'La basilique du Sacré-Cœur',
      'La cathédrale de Chartres',
    ],
    answerIndex: 1,
    source: 'Ministère de la Culture',
  },
  {
    id: 'h-cf6bf',
    category: 'histoire',
    prompt: 'Qui était une écrivaine française célèbre ?',
    choices: ['Coco Chanel', 'Édith Piaf', 'Simone de Beauvoir', 'Marie Curie'],
    answerIndex: 2,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-qb3c',
    category: 'histoire',
    prompt: 'Qui était un célèbre musicien français ?',
    choices: [
      'Wolfgang Amadeus Mozart',
      'Ludwig van Beethoven',
      'Claude Debussy',
      'Frédéric Chopin',
    ],
    answerIndex: 2,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-esun7',
    category: 'histoire',
    prompt: 'Qui était Auguste Renoir ?',
    choices: [
      'Un compositeur belge',
      'Un peintre impressionniste français',
      'Un sculpteur italien',
      'Un écrivain russe',
    ],
    answerIndex: 1,
    source: 'Livret du citoyen',
  },
  {
    id: 'h-bfg5f',
    category: 'histoire',
    prompt: 'Quelle fête est française ?',
    choices: ['Halloween', 'Thanksgiving', 'Le 14 juillet', 'La Saint-Patrick'],
    answerIndex: 2,
    source: 'Livret du citoyen',
  },

  // ────────────────────────────────────────────────────────────────────────
  // VIVRE DANS LA SOCIÉTÉ FRANÇAISE (32)
  // ────────────────────────────────────────────────────────────────────────
  {
    id: 's-47r0u',
    category: 'societe',
    prompt: 'Quel mariage est reconnu par l\'État ?',
    choices: [
      'Le mariage religieux uniquement',
      'Le mariage civil célébré à la mairie',
      'Le mariage coutumier',
      'Le mariage à l\'étranger sans formalités',
    ],
    answerIndex: 1,
    source: 'Code civil',
  },
  {
    id: 's-9mgaf',
    category: 'societe',
    prompt: 'Auprès de quelle institution les parents peuvent-ils inscrire leur enfant à l\'école publique ?',
    choices: ['La préfecture', 'Le ministère de l\'Éducation', 'La mairie', 'Le département'],
    answerIndex: 2,
    source: 'Service-public.fr',
  },
  {
    id: 's-e08s6',
    category: 'societe',
    prompt: 'En cas de divorce, qui exerce l\'autorité parentale ?',
    choices: [
      'Seulement la mère',
      'Seulement le père',
      'Les deux parents conjointement, en principe',
      'Le juge à la place des parents',
    ],
    answerIndex: 2,
    source: 'Code civil',
  },
  {
    id: 's-9cgbs',
    category: 'societe',
    prompt: 'Quelle aide permet aux personnes qui ont des difficultés financières d\'avoir un avocat ?',
    choices: ['La CAF', 'L\'aide juridictionnelle', 'Le RSA', 'L\'allocation logement'],
    answerIndex: 1,
    source: 'Service-public.fr',
  },
  {
    id: 's-bkk5r',
    category: 'societe',
    prompt: 'Où faut-il déclarer la naissance d\'un enfant ?',
    choices: [
      'À l\'hôpital uniquement',
      'À la mairie du lieu de naissance',
      'À la préfecture',
      'Au ministère de la Santé',
    ],
    answerIndex: 1,
    source: 'Code civil',
  },
  {
    id: 's-5dupn',
    category: 'societe',
    prompt: 'Quelle est l\'une des conditions pour passer l\'examen du permis de conduire ?',
    choices: [
      'Avoir au moins 17 ans et avoir réussi l\'épreuve théorique (le Code)',
      'Avoir 16 ans',
      'Avoir 21 ans',
      'Posséder un véhicule',
    ],
    answerIndex: 0,
    source: 'Service-public.fr',
  },
  {
    id: 's-6u0d9',
    category: 'societe',
    prompt: 'Un bail locatif est valide s\'il est :',
    choices: [
      'Conclu uniquement à l\'oral',
      'Écrit et signé par le bailleur et le locataire',
      'Signé devant notaire obligatoirement',
      'Validé par la préfecture',
    ],
    answerIndex: 1,
    source: 'Loi du 6 juillet 1989',
  },
  {
    id: 's-dcafb',
    category: 'societe',
    prompt: 'Où peut-on déposer un lave-vaisselle cassé ?',
    choices: [
      'Dans le bac de tri jaune',
      'Dans la poubelle classique',
      'À la déchetterie',
      'Sur le trottoir devant la mairie',
    ],
    answerIndex: 2,
    source: 'Service-public.fr',
  },
  {
    id: 's-61j7h',
    category: 'societe',
    prompt: 'Quel numéro d\'urgence permet d\'appeler la police ?',
    choices: ['Le 15 (SAMU)', 'Le 17', 'Le 18 (pompiers)', 'Le 119 (enfance en danger)'],
    answerIndex: 1,
    source: 'Service-public.fr',
  },
  {
    id: 's-d8085',
    category: 'societe',
    prompt: 'Concernant l\'accès aux soins, quelle proposition est correcte ?',
    choices: [
      'Seuls les Français ont droit aux soins',
      'Toute personne résidant en France a droit à des soins, via l\'Assurance maladie',
      'Les soins ne sont accessibles qu\'aux travailleurs',
      'Les soins sont entièrement gratuits pour tous sans assurance',
    ],
    answerIndex: 1,
    source: 'Code de la sécurité sociale',
  },
  {
    id: 's-d9a0t',
    category: 'societe',
    prompt: 'À qui est accessible la contraception ?',
    choices: [
      'Seulement aux femmes mariées',
      'À toute personne, y compris aux mineures, gratuitement et de manière confidentielle',
      'Seulement avec l\'accord des parents',
      'Seulement aux personnes de nationalité française',
    ],
    answerIndex: 1,
    source: 'Code de la santé publique',
  },
  {
    id: 's-beia1',
    category: 'societe',
    prompt: 'Qu\'est-ce que le principe de confidentialité dans le domaine de la santé ?',
    choices: [
      'Les médecins partagent toutes les informations',
      'Les informations médicales sont protégées par le secret professionnel',
      'La famille a accès au dossier sans accord',
      'L\'employeur peut consulter le dossier',
    ],
    answerIndex: 1,
    source: 'Code de la santé publique',
  },
  {
    id: 's-un1u',
    category: 'societe',
    prompt: 'L\'inscription à l\'Assurance maladie est :',
    choices: [
      'Facultative',
      'Obligatoire pour toute personne résidant en France de manière stable',
      'Réservée aux Français',
      'Limitée aux salariés',
    ],
    answerIndex: 1,
    source: 'Code de la sécurité sociale',
  },
  {
    id: 's-c3b9j',
    category: 'societe',
    prompt: 'Qui peut demander un congé parental d\'éducation ?',
    choices: [
      'Uniquement la mère',
      'Uniquement le père',
      'Tout parent salarié, mère ou père, après la naissance ou l\'adoption',
      'Uniquement les fonctionnaires',
    ],
    answerIndex: 2,
    source: 'Code du travail',
  },
  {
    id: 's-fu5ad',
    category: 'societe',
    prompt: 'Quelles sont les affaires traitées par le conseil de prud\'hommes ?',
    choices: [
      'Les litiges entre voisins',
      'Les litiges entre salariés et employeurs',
      'Les divorces',
      'Les infractions routières',
    ],
    answerIndex: 1,
    source: 'Code du travail',
  },
  {
    id: 's-fqidb',
    category: 'societe',
    prompt: 'Travailler sans être déclaré est :',
    choices: [
      'Autorisé pendant un mois',
      'Toléré pour les étudiants',
      'Interdit et puni par la loi (travail dissimulé)',
      'Légal en dessous d\'un certain salaire',
    ],
    answerIndex: 2,
    source: 'Code du travail, art. L8221-1',
  },
  {
    id: 's-s7hm',
    category: 'societe',
    prompt: 'Lorsqu\'un employeur veut qu\'un salarié travaille plus longtemps que la durée prévue dans le contrat de travail :',
    choices: [
      'Le salarié n\'a pas le choix',
      'C\'est interdit dans tous les cas',
      'Cela doit faire l\'objet d\'un accord et donner lieu à une compensation (heures supplémentaires)',
      'Cela ne peut être que bénévole',
    ],
    answerIndex: 2,
    source: 'Code du travail',
  },
  {
    id: 's-fppa4',
    category: 'societe',
    prompt: 'Quelle est la mission de France Travail ?',
    choices: [
      'Verser les retraites',
      'Accompagner les demandeurs d\'emploi et faciliter leur retour à l\'emploi',
      'Gérer les écoles',
      'Lutter contre les fraudes fiscales',
    ],
    answerIndex: 1,
    source: 'Service-public.fr',
  },
  {
    id: 's-9ul56',
    category: 'societe',
    prompt: 'Dans une entreprise, le droit syndical permet :',
    choices: [
      'D\'imposer ses vues à l\'employeur',
      'De défendre les intérêts des salariés et d\'adhérer à un syndicat',
      'De refuser de travailler quand on veut',
      'D\'exclure des collègues',
    ],
    answerIndex: 1,
    source: 'Code du travail',
  },
  {
    id: 's-knm0',
    category: 'societe',
    prompt: 'Dans une entreprise, le droit de grève autorise :',
    choices: [
      'Le sabotage des outils de travail',
      'L\'occupation des locaux à durée illimitée',
      'La cessation collective et concertée du travail pour défendre des revendications',
      'Le refus individuel de tâches précises',
    ],
    answerIndex: 2,
    source: 'Préambule Constitution 1946',
  },
  {
    id: 's-3ns1r',
    category: 'societe',
    prompt: 'Quelles sont les conditions pour toucher les allocations chômage ?',
    choices: [
      'Avoir travaillé suffisamment, être inscrit à France Travail et chercher activement un emploi',
      'Être français exclusivement',
      'Avoir 50 ans minimum',
      'Habiter en région parisienne',
    ],
    answerIndex: 0,
    source: 'Service-public.fr',
  },
  {
    id: 's-cgdom',
    category: 'societe',
    prompt: 'Qu\'est-ce que l\'école maternelle ?',
    choices: [
      'L\'école qui accueille les enfants avant l\'école élémentaire (de 3 à 6 ans)',
      'Une école religieuse',
      'Une garderie payante',
      'Une crèche',
    ],
    answerIndex: 0,
    source: 'Code de l\'éducation',
  },
  {
    id: 's-4n177',
    category: 'societe',
    prompt: 'Comment s\'appelle le diplôme passé par les élèves à la fin du collège ?',
    choices: ['Le baccalauréat', 'Le brevet (DNB)', 'Le CAP', 'Le BTS'],
    answerIndex: 1,
    source: 'Code de l\'éducation',
  },
  {
    id: 's-au4vd',
    category: 'societe',
    prompt: 'Les parents d\'élève ont le droit de :',
    choices: [
      'Choisir le programme scolaire',
      'Imposer leur enseignant préféré',
      'Participer à la vie de l\'école et être informés de la scolarité de leur enfant',
      'Refuser certaines matières',
    ],
    answerIndex: 2,
    source: 'Code de l\'éducation',
  },
  {
    id: 's-6b38o',
    category: 'societe',
    prompt: 'Qui peut manger à la cantine scolaire ?',
    choices: [
      'Seulement les élèves de nationalité française',
      'Tous les élèves, sans discrimination',
      'Seulement les élèves dont les parents travaillent',
      'Seulement les élèves d\'une religion donnée',
    ],
    answerIndex: 1,
    source: 'Code de l\'éducation',
  },
  {
    id: 's-d0es1',
    category: 'societe',
    prompt: 'À quel âge commence l\'instruction obligatoire des enfants ?',
    choices: ['3 ans', '4 ans', '6 ans', '7 ans'],
    answerIndex: 0,
    source: 'Code de l\'éducation, art. L131-1 (depuis 2019)',
  },
  {
    id: 's-rq5r',
    category: 'societe',
    prompt: 'Quel est l\'âge de la majorité ?',
    choices: ['16 ans', '18 ans', '20 ans', '21 ans'],
    answerIndex: 1,
    source: 'Code civil',
  },
  {
    id: 's-cp3bg',
    category: 'societe',
    prompt: 'À l\'école, il est interdit aux parents de :',
    choices: [
      'Rencontrer les enseignants',
      'Imposer leurs convictions religieuses ou refuser certains enseignements obligatoires',
      'Participer aux réunions',
      'Aider aux devoirs',
    ],
    answerIndex: 1,
    source: 'Charte de la laïcité à l\'école',
  },
  {
    id: 's-9arqh',
    category: 'societe',
    prompt: 'Quel motif d\'absence est accepté par l\'école ?',
    choices: [
      'Les courses',
      'La maladie de l\'enfant ou un événement familial grave',
      'Une fête religieuse non reconnue par la République',
      'Un voyage privé en cours d\'année',
    ],
    answerIndex: 1,
    source: 'Code de l\'éducation',
  },
  {
    id: 's-17bd8',
    category: 'societe',
    prompt: 'Des parents ne respectent pas l\'obligation d\'instruction pour leurs enfants. Quelle sanction maximale risquent-ils ?',
    choices: [
      'Aucune sanction',
      'Une simple mise en garde',
      'Une amende et une peine de prison',
      'La perte de la nationalité',
    ],
    answerIndex: 2,
    source: 'Code pénal, art. 227-17-1',
  },
  {
    id: 's-5ho5a',
    category: 'societe',
    prompt: 'Quand ont lieu les vacances scolaires de Noël ?',
    choices: [
      'En octobre',
      'En février',
      'En décembre-janvier (autour de Noël et du jour de l\'An)',
      'En juillet',
    ],
    answerIndex: 2,
    source: 'Calendrier scolaire — Éducation nationale',
  },
  {
    id: 's-dl59r',
    category: 'societe',
    prompt: 'À l\'école, un enfant en situation de handicap :',
    choices: [
      'Doit être scolarisé séparément',
      'A le droit d\'être scolarisé comme les autres, avec des adaptations si nécessaire',
      'Ne peut pas aller à l\'école publique',
      'N\'a pas droit à des adaptations',
    ],
    answerIndex: 1,
    source: 'Loi du 11 février 2005',
  },
];
